xtekky/gpt4free

- you/__init__.py
The output always contains '"}' along with two newlines at the end. I'm guessing this isn't intentional, so this fixes it.
> Trim remaining characters

- quora/README.md
- quora/__init__.py
- quora/api.py
1. reformatted the code in quora modules
2. added new keyword argument in Poe class for specifying driver type `chrome` or `firefox`
3. added keyword argument to specify path of cookie file
4. added keyword argument to specify driver path
> code refactor of quora module

- gui/streamlit_chat_app.py
> fix: streamlit_chat_app.py

- README.md
As the Dockerfile was moved to the root of the project we need to update the path in the README
> Fix docker build instructions

- README.md
https://chat.forefront.ai is mentioned twice.
https://github.com/xtekky/gpt4free/blob/2ae26bfa7e10bd57f9b0d2e90e4c599c816359a4/README.md?plain=1#L81-L89
> docs(readme): remove duplicate website

- gui/streamlit_chat_app.py
Conversation search result now displays conversation indices correctly, instead of a fixed range of indices from 1 to len(conversations)
> Fix index display for conversation search

- gui/streamlit_chat_app.py
Also solve a simple bug in line 121
> added option to remove conversations

- gpt4free/forefront/README.md
- gpt4free/forefront/__init__.py
- gpt4free/forefront/typing.py
- requirements.txt
forefront has added the X-Signature authentication method.
Implemented with reference to gpt4free-ts.
> Support for new authentication methods in forefront

- README.md
- gpt4free/__init__.py
- gpt4free/deepai/README.md
- gpt4free/deepai/__init__.py
- testing/deepai_test.py
This PR adds a wrapper for [deepai.org](https://deepai.org/chat). It also adds support for chat completions, via `gpt4free.ChatCompletion` or `gpt4free.deepai.ChatCompletion`.
DeepAI seems to provide unlimited `gpt-3.5-turbo` chat completions, which I have reverse engineered to be able to generate API keys for. 
See `/gpt4free/deepai/README.md` for documentation.
> Add DeepAI wrapper

- gui/streamlit_app.py
When getting a reply in Chinese, it will be garbled. Use utf-8 decoding to solve it.
> Fix Chinese garbled characters

- gui/streamlit_app.py
According to this issue #631, I think rollback back to #241 will solve most of the cases when handling special character like chinese or russian
> Rollback to #241 when handling special character 

- pyproject.toml
- requirements.txt
Other project need g4f as dependency that why I suggest to add a pyproject.toml
This pyproject is based on the previous one (inside the .v1 folder) but without poetry.
I exclude the .v1 folder
> Add pyproject.toml to build the project

- pyproject.toml
I enabled direct pip install from Git.
Sample:
```
pip install git+https://github.com/MIDORIBIN/gpt4free.git@prepare_pip_install
```
Ultimately, I believe we should make it possible to execute `pip install gpt4free` (or `pip install g4f`). However, I think xtekky should be the one to handle that task.
This pull request is the preparation for that.
> Enabled direct pip install from Git.

- .github/workflows/close-inactive-issues.yml
Way too many issues have been piling up with their authors disappearing and never closing them. At the same time, lots of the unmerged PRs remain completely unanswered due to their sheer irrelevance. Closing both would clean up a big portion of the clutter lingering on the project's page.
> Add a GitHub workflow to close inactive issues and PRs automatically

- g4f/Provider/Providers/Bing.py
The error you are encountering is related to attempting to use the default asyncio event loop within a non-main thread. asyncio expects you to use the default event loop only in the main thread.
To resolve this issue, asyncio.new_event_loop() was used instead of asyncio.get_event_loop() to create a new event loop for the current thread.
> Fix: There is no current event loop in thread.

- g4f/Provider/Providers/Ails.py
Fix arguments order
The error was:
```json
{"error":{"message":"True is not of type 'number' - 'temperature'","type":"invalid_request_error","param":null,"code":null}}
```
> Fix Ails.py

- g4f/Provider/Yqcloud.py
Hello!
A bug with requests encoding prevented a readable response from Yqcloud.
fixed by forced encoding in utf-8.
response before:
½ÑÐ¯ - Ð¼Ð¾Ð´ÐµÐ»Ñ GPT-3.5, ÑÐ¾Ð·Ð´Ð°Ð½Ð½Ð°Ñ ÐºÐ¾Ð¼Ð°Ð½Ð´Ð¾Ð¹ OpenAI. Ð¯ ÑÐ°Ð·ÑÐ°Ð±Ð¾ÑÐ°Ð½, ÑÑÐ¾Ð±Ñ Ð¿ÑÐµÐ´Ð¾ÑÑÐ°Ð²Ð»ÑÑÑ Ð¾ÑÐ²ÐµÑÑ Ð½Ð° ÑÐ°Ð·Ð»Ð¸ÑÐ½ÑÐµ Ð²Ð¾Ð¿ÑÐ¾ÑÑ Ð¸ Ð·Ð°Ð´Ð°ÑÐ¸, Ð¾ÑÐ½Ð¾Ð²Ð°Ð½Ð½ÑÐµ Ð½Ð° Ð±Ð¾Ð»ÑÑÐ¾Ð¼ Ð¾Ð±ÑÐµÐ¼Ðµ ÑÐµÐºÑÑÐ¾Ð²ÑÑ
Ð´Ð°Ð½Ð½ÑÑ
, Ð´Ð¾ÑÑÑÐ¿Ð½ÑÑ
Ð² ÐÐµÑÐ½ÐµÑÐµ. ÐÐ¾Ñ ÑÐµÐ»Ñ - Ð¿Ð¾Ð¼Ð¾ÑÑ Ð²Ð°Ð¼ Ñ Ð¸Ð½Ñ
Ð¾ÑÐ¼Ð°ÑÐ¸ÐµÐ¹ Ð¸ Ð¾ÑÐ²ÐµÑÐ°Ð¼Ð¸ Ð½Ð° Ð²Ð°Ñ Ð·Ð°Ð¿ÑÐ¾Ñ.
response after:
I am a GPT-3.5 AI model developed by OpenAI. I have a wide range of capabilities, such as understanding text, generating speech, answering questions, and even simulating conversations with people. My job is to help and provide information in response to your questions. …
> requests encoding error

- g4f/Provider/ChatgptLogin.py
https://chatgptlogin.ac redirect to https://opchatgpts.net
also sub folder/url change from `/use-chatgpt-free` to /chatgpt-free-use
for my experience this provider is slow (i think because we need 2 request to scrap wordpress nonce)
> Update link for provider ChatgptLogin

- g4f/Provider/Ails.py
- g4f/Provider/You.py
- g4f/Provider/Yqcloud.py
Unicode encoding of special characters in You's response text : {"youChatToken": "\u563f"} 
The "chat" parameter is the history of the conversation, so a "history" parameter is used.
> fix Yqcloud and You prompter using only the last message

- README.md
I've created a `document GPT`(chatPDF) which is based on "`langchain`" and "`gpt4free`".
The project initially utilized the Langchain to invoke the OpenAI model for implementing document GPT.
Now, it offers the option to use the gpt4free model, coupled with Hugging Face embedding.
**This integration enables users to use the document GPT app completely free**, without the need to input any API keys!
The [link](https://github.com/Lin-jun-xiang/docGPT-streamlit) has been added.
> Add related project: Document GPT

- interference/app.py
- requirements.txt
- setup.py
Added a `console_script` to `setup.py` to allow users to easily run the API server using the command `g4f` after installing the package.
I have also added `extras_require` so that if a user should want to use this console script, they can easily install the needed additional requirements by running `pip install g4f[api]` - It is possible that the name `server` might be preferred over `api`
> Add console script

- README.md
- interference/app.py
Adding embedding support to the interference proxy, using the all-mpnet-base-v2 model. 
I know this is already free but it can be handy in situations where you both need chat completions and embeddings.
by the way it's still kind of sketchy
> Adding embedding support to the interference proxy

- README.md
- g4f/Provider/Aivvm.py
- g4f/Provider/Bard.py
- g4f/Provider/ChatgptLogin.py
- g4f/Provider/CodeLinkAva.py
- g4f/Provider/H2o.py
- g4f/Provider/HuggingChat.py
- g4f/Provider/PerplexityAi.py
- g4f/Provider/Vitalentum.py
- g4f/Provider/__init__.py
- g4f/Provider/base_provider.py
- g4f/Provider/retry_provider.py
- g4f/__init__.py
- g4f/models.py
- testing/test_chat_completion.py
- testing/test_providers.py
Improve error handling in ChatgptLogin
Cache "snlm0e" in Bard
Fix issue: https://github.com/xtekky/gpt4free/issues/913
> Fix async example in readme

- requirements.txt
> #935 [Docker] ModuleNotFoundError: No module named 'transformers' and 'PyExecJS'

- g4f/Provider/AItianhuSpace.py
- g4f/Provider/Aivvm.py
- g4f/Provider/Vercel.py
- g4f/Provider/__init__.py
- g4f/Provider/base_provider.py
- g4f/models.py
- g4f/requests.py
"create_async" support for BaseProvider by using ThreadPoolExecutor
Default Model for Vercel
Reduced chunksize for better text completion
> AItianhuSpace Provider with GPT 4 added

- interference/requirements.txt
- requirements.txt
- Move `transformers` `tensorflow` `torch` from `/requirements.txt` to `/interference/requirements.txt`
After search through each `.py` file, I found `transformers` only imported by `interference/app.py`, this file is http server, and its deps should be save in `interference/requirements.txt`. Also, saving these deps in `/requirements.txt` may cause people who only use reverse engineering features installing unnecessary packages(which are extremly large).
#942
> Chore: move ML related deps to interference dir

- .github/workflows/publish-workflow.yaml
- Dockerfile
- docker-compose.yml
I found of that the **CI/CD workflow** for publishing image to **DockerHub** was removed. Unfortunately, I didn't find why :( (legal purposes?):
```bash
* 08291e8 - Delete ci.yml (10 weeks ago) <xtekky>
* 9b69fc6 - Add docker image ci support (6 months ago) <wengchaoxi>
```
So, I think we can use **Github Container Registry** for these purposes, aren’t we? I have created workflow which publish a new image to **Github registry** every time when a tag has been pushed.
UPD: Also I found of that **Docker compose** launch only **API** service. I have added the **GUI** service to **Docker compose**.
> Add stage to CI/CD for publishing image to Github Container Registry

- g4f/Provider/retry_provider.py
Add a timeout in retry provider in case of infinite wait to avoid stuck
> Add timeout

- g4f/Provider/retry_provider.py
- g4f/__init__.py
When using `RetryProvider`, we want to identify the specific `Provider` being used (according to #1094 requirements).
According to the source code, I noticed that `g4f.logging` is likely intended for this purpose, facilitating better debugging for developers (please correct me if I'm wrong).
However, the `logging` attribute in `retry_provider.py` does not change along with `g4f.logging = True`. (always be `False`)
https://github.com/xtekky/gpt4free/blob/cb3677a3e2bc53aba76f02e8d69c03fa9b5ab1c7/g4f/Provider/retry_provider.py#L43-L44
Therefore, in this case, I have defined `logging` as a **class variable** in `RetryProvider`.
```python
import g4f
g4f.logging = True
print(
g4f.ChatCompletion.create(
model='gpt-3.5-turbo',
messages=[{"role": "user", "content": "hello"}],
)
)
```
```
Using …
```
> Fix: debug.logging not work in retry provider

- g4f/Provider/deprecated/GetGpt.py
Try to import AES from Cryptodome.Cipher if Crypto.Cipher caused error.
> Update GetGpt provider for Debian python3-pycryptodome compatibility

- g4f/Provider/Bing.py
- g4f/Provider/ChatBase.py
- g4f/Provider/ChatForAi.py
- g4f/Provider/ChatgptX.py
- g4f/Provider/FakeGpt.py
- g4f/Provider/FreeGpt.py
- g4f/Provider/GPTalk.py
- g4f/Provider/GptForLove.py
- g4f/Provider/You.py
- g4f/Provider/Yqcloud.py
- g4f/Provider/base_provider.py
Imo, that would be a great idea to introduce a parameter that allows us to promptly verify whether the provider "natively" supports message history. But I would like to hear thoughts from other contributors about it. I am also considering adding another parameter to indicate whether a provider can perform web searches.
> [suggestion] Adding new parameter to check if a provider 'natively' supports mesage history

- g4f/api/__init__.py
- g4f/gui/server/backend.py
This Pull request made the following changes:
1. Used the config.json file to add proxy support to the API and GUI.
By meowjiao
Using ChatGPT from Chinese translate to English
> add proxy support

- g4f/gui/client/css/style.css
- g4f/gui/client/js/chat.v1.js
- g4f/gui/server/backend.py
**Part: "chat.v1.js"**
This code is an enhanced version of my previous attempt to add context. This code allows for preserving context when _refreshing the page_, _changing providers_, _changing ChatGPT models_, and _restarting the server_.
In this code, the following additions were made:
1. Separate role for ChatGPT itself to facilitate context understanding;
2. Gathering message history within the current conversation.
After collecting the message history, the obtained data is filtered and packed into an array of objects
`{'role': '...', 'content': '...'}`.
Roles are determined correctly even if multiple messages are sent simultaneously by one of the participants. When composing the list of messages, the introductory message "_Hello! How can I assist you today?_" will be ignored. …
> Adding context preservation to the GUI.

- README.md
@xtekky Fixed minor typos in `Readme.md`
> fix(typs): Fixed minor typos

- requirements.txt
PR to ensure `flask` is installed with the `async` extra. This is required when running and using the API server.
Without the dependencies installed by this extra, the following error is thrown when using the API server via `g4f api` for example
```bash
RuntimeError: Install Flask with the 'async' extra in order to use async views.
2023-10-31 19:21:47.992 | ERROR    | logging:callHandlers:1706 - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
> Install flask async extra

- g4f/gui/client/css/style.css
Currently has blank black space at the bottom of the screen on 13" devices:
> Remove height restriction

- README.md
Linked by own Issue #1252 
From previous markdown syntax.
To current available [syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts). Relative link such as navigate to Legal Notice seem providing as usual yet without bringing URL thoroughly.
> style(README): highlight markdown syntax Note section

- README.md
Docker compose is a separate binary called `docker-compose` and is not a command of `docker` itself.
> rename docker compose to docker-compose

- g4f/api/__init__.py
fixed the line where it checks if stream is requested. I made the change because before it ignored what the user typed because there was a invalid conversion from the boolean to string where the if stream clause would always be true. Simple workaround :)
> stream check workaround & fix

- g4f/Provider/ChatBase.py
70% of responses content order to contact support instead of answer. It must not be treated as normal answer and raise ValueError.
> Add back crutch of incorrect responses to ChatBase

- README.md
Fix readme example to run interference API from repo.
Running `python -m g4f.api` throws the error:
_No module named g4f.api.__main__; 'g4f.api' is a package and cannot be directly executed_
Adding the '.run' at the end of the command solves the problem.
`python -m g4f.api.run`
Below is an example.
> Fix readme example to run interference API from repo

- g4f/Provider/needs_auth/HuggingChat.py
For some reason first token from the stream on HuggingChat always starts with a whitespace. This commit strips the leading whitespace from the first token in the stream to fix this issue.
> HuggingChat: Strip leading whitespace from the first token in the stream

- g4f/Provider/Bing.py
This is a fix for an Issue that causes this error when using Bing Provider.
```
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4') 
```
Due to the specification of the aiohttp library, double quotes are escaped when cookies are passed as-is as arguments.
Therefore, it is necessary to assign the cookie directly to the Header.
Good
```
"headers": {
"Cookie": "SRCHD=AF=NOFORM; PPLState=1; KievRPSSecAuth=; SUID=; SRCHUSR=; SRCHHPGUSR=HV=9999999999", 
}
```
Bad
```
"headers": {
"Cookie": "KievRPSSecAuth=\"\"; PPLState=1; SRCHD=\"AF=NOFORM\"; SRCHHPGUSR=\"HV=9999999999\"; SRCHUSR=\"\"; SUID=\"\"", 
}
```
This problem does not occur under normal …
> Fix Bing provider Cookie issue

- g4f/Provider/FakeGpt.py
Removed the condition for filtering token_id for count 0, because count:0 is not necessarily in the list of token_ids send by the server anymore hence resulting in an empty list and causing error.
Closes #1363
> Fixed FakeGPT error caused by empty token_ids list 

- g4f/Provider/Bing.py
#1356 
I got the same error again.
```
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://www.bing.com/turing/conversation/create?bundleVersion=1.1199.4') 
```
SRCHHPGUSR needs to include the current UNIXTIME. Probably related to the time limit.
> Fix Bing provider Cookie issue 2

- g4f/debug.py
- g4f/gui/server/backend.py
This commit fixes a typo in the function name `get_lastet_version` in the g4f package. The function has been renamed to `get_latest_version`.
> fix(typo): Fix typo in function name

- g4f/Provider/Bing.py
Web search is disabled by default and can be enabled by passing `web_search = True` into `g4f.ChatCompletion.create`
> Bing: add parameter to enable/disable web search

- g4f/api/run.py
Fix error `module 'g4f.debug' has no attribute 'get_version' ` 
that occurs when running the API directly from the local repository using `python -m g4f.api.run`.
> Fix module 'g4f.debug' has no attribute 'get_version'

- README.md
After the release of version 1.0.0 of the openai python package, openai.ChatCompletion is no longer supported.
This change updates the openai example to the latest version of the package.
> Update openai example

- g4f/Provider/HuggingChat.py
- g4f/Provider/__init__.py
- g4f/Provider/bing/create_images.py
- g4f/Provider/deprecated/Aichat.py
- g4f/Provider/deprecated/Berlin.py
- g4f/Provider/deprecated/Opchatgpts.py
- g4f/Provider/deprecated/Yqcloud.py
- g4f/Provider/deprecated/__init__.py
- g4f/Provider/needs_auth/__init__.py
- g4f/Provider/selenium/AItianhuSpace.py
- g4f/Provider/selenium/MyShell.py
- g4f/Provider/selenium/PerplexityAi.py
- g4f/Provider/selenium/TalkAi.py
- g4f/Provider/selenium/__init__.py
> Improve CreateImagesBing

- g4f/Provider/Phind.py
Phind added new additional tags to their reply and this commit removed them.
Example additional tags:
```
<PHIND_SPAN_BEGIN>{"id": "g30s0idmy56038rjky0i", "indicator": "Using GPT4", "parent": "qolbkr9srwccc7ir3m5f", "start": 1706418122.9927964, "end": null, "indent": 2, "children": []}</PHIND_SPAN_BEGIN><PHIND_SPAN_END>{"id": "g30s0idmy56038rjky0i", "indicator": "Using GPT4", "end": 1706418122.994516}</PHIND_SPAN_END>
```
> remove additional tags in Phind

- g4f/webdriver.py
I had some problems with the hardcoded webdriver path, so:
1. Discover chromedriver dynamically with "which". 
2. Use "finally" in WebDriverSession.__exit__
> Fix chromedriver path

- g4f/image.py
I encountered an issue while attempting to send an image to Bing Copilot yesterday... I got the following error:
```
2024-02-10 11:29:02 gpt4free-1  | INFO:werkzeug:172.19.0.1 - - [10/Feb/2024 14:29:02] "POST /backend-api/v2/conversation HTTP/1.1" 200 -
2024-02-10 11:29:04 gpt4free-1  | ERROR:root:tuple index out of range
2024-02-10 11:29:04 gpt4free-1  | Traceback (most recent call last):
2024-02-10 11:29:04 gpt4free-1  |   File "/app/g4f/gui/server/backend.py", line 185, in _create_response_stream
2024-02-10 11:29:04 gpt4free-1  |     for chunk in ChatCompletion.create(**kwargs):
2024-02-10 11:29:04 gpt4free-1  |   File "/app/g4f/Provider/base_provider.py", line 201, in create_completion
2024-02-10 11:29:04 gpt4free-1  |     yield loop.run_until_complete(gen.__anext__())
2024-02-10 …
```
> Fix process_image to handle transparency correctly

- g4f/Provider/GeminiChatbotSigma.py
- g4f/Provider/GeminiProChat.py
Since GeminiProChat is down I decided to take the existing provider file and adapt it for https://gemini-chatbot-sigma.vercel.app/ which is a provider with the same backend and frontend, just a different name. That one actually works.
Merging this would close #1596
> Move GeminiProChat to a new provider #1596

- etc/tool/translate_readme.py
1.Change uses of whitelist to allowlist in translate_readme.py.
2.Change uses of blacklist to blocklist in translate_readme.py.
3.Change uses of blacklisted to blocklisted in translate_readme.py.
> Change uses of whitelist to allowlist in translate_readme.py.

- g4f/api/__init__.py
Run interference API from PyPi package results in a _TypeError: 'Api' object is not callable_ when attempting to make a request.
The adjustment ensures that the bug is fixed while keeping the same functionalities, including the _use_colors_ or run interference API from repo
> Fix TypeError: 'Api' object is not callable

- g4f/gui/client/css/style.css
The spacing was misaligned, a little increase in the width fixes it
before:
after:
on chrome, mac air m2
> ~ gui system prompt spacing

- .github/workflows/publish-workflow.yaml
- docker/Dockerfile
When I started this project with Docker on my MacBook Pro M1 chip, I found that Chrome would get an error, probably because Chrome only supports the 4K Pagesize AMD64 platform, not Arm64. After investigating, the current `seleniumnode/chrome` image used by the dockerfile only supports amd64. The selenium community is already pushing for the arm64 merge https://github.com/SeleniumHQ/docker-selenium/issues/1847. For the time being, we are using the base image `seleniarm/node-chromium` that supports both arm64 and amd64 to ensure dual-architecture support. 
Currently, arm64 images support Pagesize 4k kernels, and there is no support plan for Pagesize 64k in the short term (Chrome does not support 64k Pagezie).
> feat: docker add arm64 support

- g4f/Provider/Liaobots.py
Changes proposed:
- Rename `gpt-4-plus` to `gpt-4` in Liaobots to align with the naming conventions of other providers' models.
- Retain the `id` and `name` fields as "gpt-4-plus" to match the external service's API endpoints.
> Align Model Naming with Provider Standards for ChatCompletion Compatibility

- g4f/Provider/needs_auth/Gemini.py
The error is as follows:
```plain text
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lh3.googleusercontent.com:443 ssl:default [Connect call failed ('172.217.163.33', 443)]
```
fix issue: Gemini.py missing proxy setting at line 141 and 143
> Fix Gemini Proxy Connect call failed

- g4f/Provider/openai/har_file.py
Addresses the following uncaught exception:
```py
ERROR:root:'text'
Traceback (most recent call last):
File "/app/g4f/gui/server/api.py", line 229, in _create_response_stream
for chunk in ChatCompletion.create(**kwargs):
File "/app/g4f/providers/base_provider.py", line 206, in create_completion
yield loop.run_until_complete(await_callback(gen.__anext__))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/app/g4f/providers/base_provider.py", line 202, in await_callback
return await callback()
^^^^^^^^^^^^^^^^
File "/app/g4f/Provider/needs_auth/OpenaiChat.py", line 360, in create_async_generator
arkose_token, api_key, cookies = await …
```
> Don't give up searching for accessToken in HAR file

- g4f/models.py
**codellama/CodeLlama-34b-Instruct-hf** - Removed, no longer available for free
**mistralai/Mistral-7B-Instruct-v0.1** - Removed, no longer available for free
**jondurbin/airoboros-l2-70b-gpt4-1.4.1** - Removed, not available anymore
**mistralai/Mistral-7B-Instruct-v0.2** - Added new model
**mistralai/Mixtral-8x22B-v0.1** - Added, but commented out because it doesn't work (yet?) with OpenAI async_generator. Perhaps we need to change the implementation in DeepInfra.py for it to work.
> Update DeepInfra models

- g4f/client/async_client.py
Fixing this error:
```
unsupported operand type(s) for ** or pow(): 'str' and 'dict'
```
> Fixing an error that occurs due to a missing comma in async client

- g4f/Provider/Bing.py
- g4f/Provider/Chatgpt4Online.py
- g4f/Provider/DuckDuckGo.py
- g4f/Provider/FlowGpt.py
- g4f/Provider/PerplexityLabs.py
- g4f/Provider/bing/conversation.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/server/api.py
- g4f/requests/curl_cffi.py
Fix DuckDuckGo Provider issues
Fix PerplexityLabs, FlowGpt Provider
Update Bing, Gemini Provider
> Updates for some providers

- examples/ecosia.py
- g4f/Provider/Ecosia.py
- g4f/Provider/You.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/OpenRouter.py
- g4f/Provider/needs_auth/Openai.py
- g4f/Provider/needs_auth/OpenaiAccount.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/__init__.py
- g4f/api/__init__.py
- g4f/gui/client/index.html
- g4f/providers/base_provider.py
Use AsyncClient in API, add web_search parameter in API Improve error messages in Openai
> Add Ecosia Provider, Add OpenaiAccount alias

- README.md
- g4f/Provider/FlowGpt.py
- g4f/Provider/HuggingChat.py
- g4f/Provider/Llama.py
- g4f/Provider/__init__.py
- g4f/gui/client/index.html
- g4f/gui/client/static/js/chat.v1.js
- g4f/models.py
Decided to change llama2.py to llama.py to hold all the llama family models.
Closes https://github.com/xtekky/gpt4free/issues/1855
Roadmap:
- Add compatible providers (like DeepInfra, etc.)
> Added Meta llama-3 support!

- g4f/api/__init__.py
- g4f/cli.py
May we need authorization for building apps on g4f.
I made a simple implementation for the API mode.
> add authorization for g4f API

- g4f/api/__init__.py
- g4f/client/stubs.py
- g4f/typing.py
When using the openai-node library,
the following error occurs in the code below due to a missing implementation of OpenAI's API.
```javascript
import OpenAI from 'openai';
const openai = new OpenAI({
apiKey: "gpt4free",
baseURL: "http:///gpt4free-api.url/v1",
});
stream = await openai.beta.chat.completions
.stream({
"model":"gpt-3.5-turbo",
"stream":true,
"messages":[{"role":"user","content":"Hello!"}],
});
for await (const chunk of stream) {
console.log(chunk.choices[0]?.delta?.content || '');
}
```
```
OpenAIError: stream ended without producing a ChatCompletionMessage with role=assistant
```
> Improve compatibility of openai-node

- g4f/providers/base_provider.py
Check if currently running loop is uvloop patched and do not nest patch it due to incompatibility between the two.
error stack:
```python
File "/usr/local/lib/python3.11/site-packages/g4f/client/client.py", line 114, in create
return response if stream else next(response)
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/g4f/client/client.py", line 53, in iter_append_model_and_provider
for chunk in response:
File "/usr/local/lib/python3.11/site-packages/g4f/client/client.py", line 28, in iter_response
for idx, chunk in enumerate(response):
File "/usr/local/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 95, in create_completion
raise_exceptions(exceptions)
File "/usr/local/lib/python3.11/site-packages/g4f/providers/retry_provider.py", line 231, in …
```
> Update base_provider: Do not nest patch uvloop loop.

- g4f/locals/models.py
It will create a models directory in current folder if it can't find the directory due to previous way where it tries to return models directory where its not present which in turns returns None causing os.path to fail Fix #2030
> Update models.py to create models directory when its not present

- g4f/Provider/HuggingChat.py
- Fix null string in response token temporarily 
- Add new model `01-ai/Yi-1.5-34B-Chat` that works well using Japanese.
> Update `HuggingChat` provider

- g4f/Provider/openai/har_file.py
Fixes  https://github.com/xtekky/gpt4free/issues/2035 and https://github.com/xtekky/gpt4free/issues/2040. The access token extraction process has been updated. Previously, the access token was retrieved from the .har file in JSON format from the endpoint https://chatgpt.com/api/auth/session. Now, the access token is passed directly in the first response.
> Fix har openai access token parsing

- g4f/Provider/GeminiPro.py
Adding gemini-1.5-flash on GeminiPro provider.
Google is deprecating Gemini 1.0 Pro Vision model suggesting to use Gemini 1.5 Flash or Gemini 1.5 Pro as reported [here](https://ai.google.dev/gemini-api/docs/models/gemini)
`Note: The Gemini 1.0 Pro Vision model will be deprecated from Google AI services and tools as of June 12, 2024 (does not apply to Vertex AI). You'll be able to use Gemini 1.0 Pro Vision until July 12, 2024. After July 12, saved prompts using Gemini 1.0 Pro Vision in Google AI Studio will switch to using Gemini 1.5 Flash. API calls that specify Gemini 1.0 Pro Vision will fail so we recommend switching to Gemini 1.5 Flash or 1.5 Pro.`
> add gemini-1.5-flash to GeminiPro provider

- README.md
Change all instances of `chat.openai.com` in README.md to `chatgpt.com` since that's the official domain now.
> Replace chat.openai.com with chatgpt.com

- g4f/Provider/needs_auth/OpenaiChat.py
This pull request addresses a recent change in ChatGPT's backend that modified the way Arkose detection is signaled in API responses.
Previously, the code relied on checking the `requirements["arkose"]["required"]` flag to determine if an Arkose token was necessary. However, ChatGPT has adjusted its API, and this information is now nested within a `text` key within the `requirements` object. This change breaks the existing Arkose detection logic.
This PR modifies the `create_async_generator` function to correctly interpret the updated Arkose detection mechanism.
**Here's how the code is updated:**
**Original code:**
```python
as response:
cls._update_request_args(session)
await raise_for_status(response)
requirements = await response.json()
need_arkose = requirements.get("arkose", …
```
> ChatGPT Reverse Engineering Update: Adapting to Arkose Detection Changes

- g4f/Provider/DDG.py
According to [https://duckduckgo.com/aichat](https://duckduckgo.com/aichat), DDG has supported gpt-4o-mini, replacing gpt-3.5-turbo.
This PR removes gpt-3.5-turbo, adds gpt-4o-mini for DDG provider.
Modified `g4f/Provider/DDG.py`: 
- Removed `gpt-3.5-turbo-0125` model, added `gpt-4o-mini` model.
- Setup aliases for `gpt-4` and `gpt-4o`, both linked to `gpt-4o-mini`
> feat: GPT-4o-mini support for DDG provider

- g4f/gui/server/internet.py
Fix DDG web search 'await' expression error in Python 3.12.6
- Resolve "object list can't be used in 'await' expression" error 
https://github.com/xtekky/gpt4free/issues/2236
When attempting to perform a web search using DuckDuckGo (DDG), an error occurs:
"Couldn't do web search: object list can't be used in 'await' expression"
ddgs.text changed to ddgs.atext for supporting await
> Duck Duck Go Async Text Search Bug Fix

- g4f/api/__init__.py
**Issue**
Interference API server doesn't support CORS protocol, so it can't handle **OPTIONS** preflight requests.
Issue #2006 shows a failed fetch request from browser and suggests a possible solution.
This feature is needed because local hosted browser apps can't call the API server, failing with CORS error mentioned in #2006.
**Proposed Solution**
Implement **FastAPI CORSMiddleware** handler.
**Info:** According to [FastAPI documentation](https://fastapi.tiangolo.com/tutorial/cors/), if allow_origins is set to ['\*'], credentials (Cookies, Authorization headers...) are not allowed, so origins must be specified to comply with [fetch() Browser standard](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials).
So I follow this alternative solution [Puzzling  error with FastAPI's …
> Add support for CORS preflight OPTIONS requests (#2006)

- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/client/static/js/highlightjs-copy.min.js
- g4f/version.py
**Issue**
**Clipboard API** may fail if web page is not deemed a **Secure Context**,  causing issue #2287 [MDN Clipboard documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations). 
[This MDN page](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) claims **localhost** origins are deemed secure, but decision may involve other [environment factors](https://w3c.github.io/webappsec-secure-contexts/#localhost) so it can't be guaranteed.
**Proposed Solution**
- Add error checking to **Clipboard API** and fallback to `browser.exec("copy")` if required.
- Use async syntax in **highlight.js** copy plugin
**Info:** There are two copy buttons. One of them uses **highlight.js** copy plugin, so I will open an issue there.
> Fix Clipboard copy bug (issue #2287)

- g4f/Provider/GeminiPro.py
Normally response has property 'finishReason' equal to 'STOP' and non-None 'content' property. However, if request to Gemini models does not fit Google's policies, returned response does not contain 'content' property and server returns status code 500 trying to find property 'parts' of None type.
Example `data['candidates'][0]`:
```
{
'finishReason': 'SAFETY',
'index': 0,
'safetyRatings': [
{'category': 'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'probability': 'NEGLIGIBLE'},
{'category': 'HARM_CATEGORY_HATE_SPEECH', 'probability': 'MEDIUM'},
{'category': 'HARM_CATEGORY_HARASSMENT', 'probability': 'MEDIUM'},
{'category': 'HARM_CATEGORY_DANGEROUS_CONTENT', 'probability': 'NEGLIGIBLE'}
]}
```
> Tiny handler for unexpected finishReason of GeminiPro provider

- .github/workflows/auto-pr-description.yml
🎉 **Feature Addition: Auto-generate Pull Request Descriptions!** 🎉
This PR introduces a new GitHub Actions workflow that automatically generates descriptions for pull requests when they are opened or synchronized. 
- 🛠️ Added a new workflow file: `.github/workflows/auto-pr-description.yml`
- 🔄 The workflow triggers on pull request events (opened and synchronized).
- 🚀 Utilizes the `yuri-val/auto-pr-description-g4f-action` to create informative PR descriptions automatically.
- https://github.com/yuri-val/auto-pr-description-g4f-action
- https://github.com/marketplace/actions/auto-generate-pr-description-g4f
- 📋 Saves time by automating PR description generation.
- 🔍 Enhances clarity and consistency in pull request management.
Let's streamline our workflow and improve collaboration! 🚀
> Auto-generate PR description [G4F]

- docs/async_client.md
- docs/client.md
- g4f/Provider/Copilot.py
- g4f/api/__init__.py
- g4f/cli.py
- g4f/gui/client/static/css/style.css
Update provider in Vision documentation
> Add .har file support for Copilot

- g4f/Provider/Airforce.py
https://api.airforce/imagine2?model=flux-4o
https://api.airforce/imagine2?model=flux-schnell 
and
https://api.airforce/imagine2?model=flux-1.1-pro
all generate same images but "Flux-1.1-Pro" doesnt work
> FIX: Bug fix for flux-pro aka flux-schnell

- docker/Dockerfile-armv7
#2349 #2427
This should fix missing headers for **cffi** and **pillow** libraries.
> Fix docker armv7 cffi pillow

- docker/Dockerfile-armv7
#2349 
This should fix **cryptography** module build error.
We can't clean up rust with `rustup self uninstall -y` because there's a bug `Value too large` [link](https://www.github.com/rust-lang/cargo/issues/8719), but we can remove `.rustup` folder.
> Fix docker armv7 cryptography module build

- g4f/Provider/needs_auth/GeminiPro.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/api/__init__.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/providers/base_provider.py
Fix reading model list in GeminiPro
Fix  check content-type in OpenaiAPI
> Update provider parameters, check for valid provider

- g4f/client/__init__.py
When using reasoning models like deepseek-r1 and sonar-reasoning, an error occurs. Here is my small fix.
Using PerplexityLabs provider and sonar-reasoning model
Traceback (most recent call last):
File "....py", line 44, in <module>
response = client.chat.completions.create(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../.venv/lib/python3.12/site-packages/g4f/client/__init__.py", line 281, in create
return next(response)
^^^^^^^^^^^^^^
File ".../.venv/lib/python3.12/site-packages/g4f/client/__init__.py", line 117, in iter_append_model_and_provider
for chunk in response:
^^^^^^^^
File "..../.venv/lib/python3.12/site-packages/g4f/client/__init__.py", line 76, in iter_response
chunk = str(chunk)
^^^^^^^^^^
TypeError: __str__ returned non-string (type list)
> Fix error __str__ returned non-string (type list) when using reasonin model

- docs/providers-and-models.md
- etc/examples/vision_images.py
- g4f/Provider/AllenAI.py
- g4f/Provider/Blackbox.py
- g4f/Provider/Copilot.py
- g4f/Provider/DeepInfraChat.py
- g4f/Provider/Dynaspark.py
- g4f/Provider/Goabror.py
- g4f/Provider/LambdaChat.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/Websim.py
- g4f/Provider/__init__.py
- g4f/Provider/hf_space/BlackForestLabs_Flux1Dev.py
- g4f/Provider/hf_space/BlackForestLabs_Flux1Schnell.py
- g4f/Provider/hf_space/CohereForAI_C4AI_Command.py
- g4f/Provider/hf_space/DeepseekAI_JanusPro7b.py
- g4f/Provider/hf_space/G4F.py
- g4f/Provider/hf_space/Microsoft_Phi_4.py
- g4f/Provider/hf_space/Qwen_QVQ_72B.py
- g4f/Provider/hf_space/Qwen_Qwen_2_5M_Demo.py
- g4f/Provider/hf_space/Qwen_Qwen_2_72B_Instruct.py
- g4f/Provider/hf_space/StabilityAI_SD35Large.py
- g4f/Provider/hf_space/Voodoohop_Flux1Schnell.py
- g4f/Provider/hf_space/__init__.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/models.py
- g4f/tools/run_tools.py
This PR introduces new providers (Websim, Dynaspark, LambdaChat, Goabror) and updates existing provider configurations throughout the codebase. It enhances documentation with standardized terminology and adds audio generation indicators to provider tables. The PR also improves UI labeling for HuggingFace integrations and updates model configurations for various providers.
- Add "Audio generation" column to all provider tables with ❌ defaults
- Rename table headers: "Text Models" → "Text generation", "Image Models" → "Image generation", "Stream" → "Streaming"
- Add new providers: ARTA, Dynaspark, Websim with respective capabilities
- Update PollinationsAI row with audio generation support and additional vision models
- Rename HuggingSpace providers to use underscores (e.g. …
> Add new providers and enhance existing provider configurations

- g4f/Provider/DDG.py
- [fix] Replace "x-vqd-hash-1" header extraction with random hash in g4f/Provider/DDG.py
- [refactor] Adjust conditional to return generated hash when vqd exists in g4f/Provider/DDG.py
- [fix] Prevent updating conversation.vqd_hash_1 from response headers to avoid ERR_CHALLENGE
fix #2839 
fix #2813
> fix: fix DDG ERR_CHALLENGE

- README.md
I guess all Python commands should be run inside the container.
> Fix Slim Docker instructions

- .gitignore
- docs/providers-and-models.md
- etc/tool/commit.py
- g4f/Provider/ARTA.py
- g4f/Provider/AllenAI.py
- g4f/Provider/Blackbox.py
- g4f/Provider/DDG.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/PollinationsImage.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/models.py
[docs: update providers documentation and enhance support for Blackbox HAR auth](https://github.com/xtekky/gpt4free/pull/2886/commits/54ef1a511ce9aad82fd7108f9b6adb3f412c2e64)
- Added "No auth / HAR file" authentication type in providers-and-models.md
- Added "Video generation" column to provider tables for future capability
- Updated model counts and provider capabilities throughout documentation
- Fixed ARTA provider with improved error handling and response validation
- Enhanced AllenAI provider with vision model support and proper image handling
- Significantly improved Blackbox provider:
- Added HAR file authentication support
- Added subscription status checking
- Added premium/demo model differentiation
- Improved session handling and error recovery
- Enhanced DDG provider with …
> Update providers documentation and enhance support for Blackbox HAR auth

- g4f/api/stubs.py
- Parse `size` string (e.g., "256x256") to auto-set `width` and `height`
- Keep explicit `width`/`height` priority if both provided
Fixes xtekky#2902
> fix(ImageGenerationConfig): add size="WxH" support

- g4f/client/stubs.py
Fix a typo in the `object` field from "chat.completion.cunk" to "chat.completion.chunk".
> fix(g4f/client/stubs.py): correct typo in object field

- g4f/Provider/Blackbox.py
- g4f/Provider/Cloudflare.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/models.py
- In **g4f/Provider/Cloudflare.py**:
- Added `from .helper import to_string`.
- Replaced conditional string checks with `to_string(message["content"])` for both `"content"` and elements in `"parts"`.
- In **g4f/Provider/PollinationsAI.py**:
- Removed `"o3-mini"` from the `vision_models` list.
- Updated the alias mapping dictionary by:
- Removing the `"o3-mini": "openai-reasoning"` entry.
- Removing the duplicate `"gpt-4o-mini": "searchgpt"` mapping.
- Removing the duplicate `"gemini-2.0-flash-thinking": "gemini-reasoning"` entry.
- Removing the `"qwq-32b": "qwen-reasoning"` mapping.
- Adding a new alias `"llama-4-scout": "llamascout"`.
- In **g4f/gui/client/static/css/style.css**:
- Changed the `border-left` property value from `var(--colour-4)` to `var(--media-select)`.
- In …
> refactor: update string conversion, provider aliases, and model mappings

- g4f/api/__init__.py
Corrected access to ProviderUtils by using its full path g4f.Provider.ProviderUtils.
> Fix: Resolve NameError in provider info endpoint (#2941)

- g4f/client/stubs.py
**Problem**:
content with value None is serialized as `"None"` string in response when using stream mode:
> fix: serialize None as empty string

- g4f/api/__init__.py
Refactored the import statements in the Api module to directly reference Provider.ProviderUtils instead of an indirect import. Also removed a duplicate import of the Provider module to avoid redundancy.
> Refactor: Update Provider import paths in Api module

- etc/tool/commit.py
- g4f/Provider/Cloudflare.py
- g4f/Provider/Copilot.py
- g4f/Provider/audio/EdgeTTS.py
- g4f/Provider/audio/gTTS.py
- g4f/Provider/har/__init__.py
- g4f/Provider/hf/HuggingFaceMedia.py
- g4f/Provider/hf_space/CohereForAI_C4AI_Command.py
- g4f/Provider/needs_auth/Grok.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/client/__init__.py
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/providers/base_provider.py
- g4f/tools/files.py
- g4f/version.py
- **g4f/Provider/har/__init__.py**
- `get_models`/`create_async`: iterate over `(domain, harFile)` and filter with `domain in request_url`
- `read_har_files` now yields `(domain, har_data)`; fixes file variable shadowing and uses `json.load`
- remove stray `print`, add type hint for `find_str`, replace manual loops with `yield from`
- small whitespace clean-up
- **g4f/Provider/needs_auth/Grok.py**
- `ImagePreview` now passes `auth_result.cookies` and `auth_result.headers`
- **g4f/Provider/needs_auth/OpenaiChat.py**
- add `Union` import; rename/refactor `get_generated_images` → `get_generated_image`
- support `file-service://` and `sediment://` pointers; choose correct download URL
- return `ImagePreview` or `ImageResponse` accordingly and stream each image part
- propagate 422 errors, …
> feat: enhance HAR provider, image handling, markdown upload & cache

- g4f/Provider/TypeGPT.py
- g4f/Provider/audio/MarkItDown.py
- g4f/Provider/hf_space/Qwen_Qwen_3.py
- g4f/Provider/hf_space/__init__.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/api/__init__.py
- g4f/providers/any_provider.py
- g4f/tools/files.py
- Introduce `Qwen_Qwen_3` provider in `g4f/Provider/hf_space/Qwen_Qwen_3.py`
- Register Qwen_Qwen_3 in `g4f/Provider/hf_space/__init__.py` and add it to `HuggingSpace`
- Update `MarkItDown` in `g4f/Provider/audio/MarkItDown.py` to accept and forward `llm_client` and `llm_model` kwargs; add async handling for `text_content`
- Modify audio route in `g4f/api/__init__.py` to pass `llm_client` for MarkItDown and set `modalities` only for other providers
- Adjust `OpenaiChat` (needs_auth) to merge media for upload and check for media presence before requesting images
- Change `get_tempfile` in `g4f/tools/files.py` to determine suffix from file extension using `os.path.splitext`
- Refactor provider listing and model mapping in `AnyProvider.get_models()` (g4f/providers/any_provider.py) to update …
> feat: add Qwen Qwen-3 provider and update audio/media handling

- README.md
- g4f/Provider/Cloudflare.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/client/__init__.py
- Changed documentation URL in README.md for detailed guidance link
- In g4f/Provider/Cloudflare.py, broadened exception handling in async argument fetching to catch all exceptions in one place and only specific exceptions in another
- In g4f/Provider/PollinationsAI.py, removed raising of exception for unknown model not in image_models and replaced it with pass
- In g4f/Provider/needs_auth/OpenaiChat.py, modified session post call to always use cls._headers
- Changed if-chain in OpenaiChat.py to use elif for checking element prefix "sediment://"
- Added logic to extract and yield generated images for unique "file-service://" matches in streamed responses within OpenaiChat.py
- Commented out multimodal_text image asset pointer handling in OpenaiChat.py
- In g4f/client/__init__.py …
> fix: update error handling, URL, and media name logic across providers

- g4f/Provider/LambdaChat.py
- g4f/Provider/hf_space/CohereForAI_C4AI_Command.py
- g4f/client/stubs.py
- Introduced `import random` in g4f/Provider/LambdaChat.py and g4f/Provider/hf_space/CohereForAI_C4AI_Command.py
- Replaced the direct lookup with `random.choice(alias)` when `alias` is a list in both provider files
- Updated debug log messages to include class name (`{cls.__name__}`) instead of hardcoded string
- Removed `model_config = {"arbitrary_types_allowed": True}` from g4f/client/stubs.py
- Corrected indentation of `@classmethod` decorator in stubs.py to align with method definition
- Clarified that `model_construct` in stubs.py calls `super().model_construct` with role="assistant" and filtered arguments
> fix: add random.choice for alias selection and fix stub model_construct

- g4f/Provider/needs_auth/OpenaiChat.py
OpenaiAccount Completions API adds ids from /message/metadata/refresh_key_info event to the response if image generation is used
> fix: ignore /message/metadata/refresh_key_info

- g4f/providers/retry_provider.py
When using a model like `gemini-2.5-flash` and the provider `Gemini GeminiPro LegacyLMArena HarProvider`, the server will use `retry_provider`. Although the API key was sent in the format:
```
{'GeminiPro': 'AIzaSyBRjxgxSMBHVTwwMev4hs5QeDtgczzyb6s'}
```
when the `Gemini` provider failed, `GeminiPro` reported that it did not receive the API key.
> keep api_key for next provider when use retry_provider

- g4f/Provider/GLM.py
This PR enables the "thinking" (reasoning) stream for the GLM provider (`chat.z.ai`). 
The provider's code was already set up to handle `thinking` events, but the API requires the `"enable_thinking": True` flag to be explicitly sent in the request payload to start sending these events. This flag was previously missing, causing the feature to not work.
- Modified the `data` payload in the `create_async_generator` method within the `GLM` provider class.
- Added the `"features": {"enable_thinking": True}` dictionary to the JSON request body.
Without this change, the GLM provider could not stream the model's reasoning process, negatively impacting the user experience as it would appear the model was idle. This fix activates the intended functionality and aligns the provider with its full …
> feat(provider/GLM): Enable reasoning/thinking stream
