- quora/mail.py
> unpatch mail

- quora/mail.py
> Revert "unpatch mail"

- quora/api.py
> Fix typo in api.py

- README.md
- cocalc/__init__.py
Add cocalc to gpt4free
Most likely 3.5
Unknown internet connectivity
#64
> Add cocalc

- README.md
- ora/README.md
- quora/README.md
Fixed some typos on
- README.md             # reasoning model
-  ora/README.md     # import ora
- quora/README.md  # make sure
> Fix typos in READMEs

- README.md
Small changes to README in favor of readability, nothing major.
> Grammar suggestions in README

- README.md
In line 17 the word "install" was missing the "s"!
> Spelling check

- Docker/Dockerfile
- README.md
> Dockerization

- .gitignore
- quora/README.md
- quora/__init__.py
- quora/api.py
- quora/mail.py
- requirements.txt
- added new class `Poe` this will be used as an entry point
-  added selenium for signup/login into poe.com
-  added code to save cookie to a file, this will be used from next time onwards, if expires it will try to register again
-  added fake-useragent module, we can use this instead of static string
> Fix for Poe account creation

- phind/__init__.py
Phind Search.create now raises ValueError if missing cf_clearance.
> fixes #143 missing cf_clearance raises error

- README.md
* I turned the table of contents into an actual table and added the new sections as well (docker, GUI, etc).
* I made a Colab notebook with a quora example usage
* I added a status column to specify which APIs are active or not
I didn't add the notebook file to the repo because I might change it constantly, but you can check it out [here](https://github.com/DanielShemesh/gpt4free-colab/blob/main/gpt4free.ipynb)
btw I noticed you already removed some of the APIs, but I still left them in the table of contents as "inactive", but you can remove those rows completely from the table I made
> Update README.md + made a Jupyter notebook

- README.md
update new gpt4/gpt3.5 website https://chat.forefront.ai/
> update new gpt4/gpt3.5 website https://chat.forefront.ai/

- README.md
> Update README.md - automatic star count update

- testing/you_test.py
- you/README.md
- you/__init__.py
1. updated you code to return error message in case of no response from the api request
2. updated regex for parsing response
> code refactor

- gui/streamlit_app.py
- quora/mail.py
- unfinished/bard/__init__.py
- unfinished/bard/typings.py
- unfinished/bing/__ini__.py
- unfinished/cocalc/__init__.py
- unfinished/easyai/main.py
- unfinished/gptbz/__init__.py
- unfinished/openai/__ini__.py
Title: Code improvements and optimizations
Description:
- Refactored code for better readability and maintainability
- Optimized performance by reducing unnecessary computations
- Fixed potential bugs and edge cases
- Updated documentation and comments for clarity
These changes aim to enhance the overall quality of the codebase and make it easier for other contributors to understand and work with the project. Please review the changes and let me know if any further modifications are required.
> As you said, I updated the ./unfinished directory to resembel a professional codebases. 

- theb/README.md
A print statement to add a newline after iterating through the loop
> updated README.md

- README.md
> Update README.md : typo fix

- gui/streamlit_app.py
gui need escape unicode answer to support Chinese
> escape unicode answer

- unfinished/chatpdf/__init__.py
There is still work to be done
> chatpdf.com reversed API (initial)

- unfinished/openai/README.md
corrected "refractoring" to "refactoring"
> typo correction

- README.md
Should be discord.gg, discord.com leads to a 404 page.
> Update README.md with correct Discord link

- forefront/__init__.py
> Print the mail messages only when logging

- openaihosted/__init__.py
- openaihosted/readme.md
- testing/openaihosted_test.py
Modify openaihosted code, convert some escape sequences code. Make messages parameter so user can include the conversation history to helps retain context of previous conversation.
> changes to openaihosted

- gui/streamlit_chat_app.py
just like the fix in streamlit_app.py
> Fix unicode error in streamlit_chat_app.py

- gpt4free/forefront/__init__.py
- gpt4free/quora/__init__.py
- gpt4free/theb/__init__.py
- gpt4free/you/__init__.py
- gui/query_methods.py
- gui/streamlit_chat_app.py
I've added proxy setting in GUI and library.
If proxy url like `127.0.0.1:7890` is provided, then this library will use this proxy to request.
> Feat: add proxy settings in GUI and library.

- gpt4free/quora/backup-mail.py
Emailnator seems to be a bit unstable, and there may be emails already in the original mailbox. 
This code is completely modeled after the original Mail.py.
> backup options to Emailnator

- gui/streamlit_chat_app.py
the known bug has been fixed when trying to load a conversation and etc, the bug on the README
> fixed: bug fix on GUI

- README.md
- docker-compose.yaml
- gpt4free/cocalc/__init__.py
Added some docstrings because it took some time to understand the code.
Provided type hints.
Moved constant related variables to class constants.
Added an exception statements, hence the code is more robust.
> refactor(gpt4free/cocalc/__init__.py): Refactored init file

- gpt4free/you/README.md
- Fixed you example in the README.md to use the pydantic model
> fix you README

- .github/workflows/ci.yml
Required:
1. [A Docker Hub Account](https://hub.docker.com/signup)
2. [Setup Github Secrets](https://github.com/xtekky/gpt4free/settings/secrets/actions): `DOCKER_USERNAME`, `DOCKER_PASSWORD`
> Add docker image ci support

- gui/streamlit_chat_app.py
Commit 1: `st.session_state['current_conversation'] = st.session_state.conversations[idx]` -> `st.session_state['current_conversation'] = conversation`
Commit 2: Add searchbar for conversations. Results are sorted by Levenshtein distance.
> Add searchbar for conversations

- requirements.txt
add Levenshtein in requirements.txt for gui/streamlit_chat_app.py
> add Levenshtein in requirements.txt for gui/streamlit_chat_app.py

- README.md
Fixed small capitalization typos
> docs: Update README.md / fix typo

- .dockerignore
- Dockerfile
| image                         | size   |
|-------------------------------|--------|
| original Dockerfile           | 1.58GB |
| with .gitignore              | 1.41GB |
| with .gitignore + refactoring | 634MB  |
> Dockerfile optimization

- gpt4free/theb/__init__.py
add timeout argument to solve timeout issue with long response message
> Solve 'Operation timeout after 30000 milliseconds' error

- README.md
I have written a TypeScript version of GPT4Free based on your project and I hope to join the GPT4Free family with my contribution.
I have only implemented model for you.com, but I hope to join your project in order to attract more people to join and integrate more models.
> gpt4free typescript version

- gpt4free/theb/__init__.py
This change will replace any invalid UTF-8 characters with the Unicode replacement character (U+FFFD) and should prevent the UnicodeDecodeError from occurring.
> This should prevent the UnicodeDecodeError in theb

- .vscode/settings.json
- gpt4free/forefront/__init__.py
- gpt4free/test.py
Just changed the temp email library to xtempmail and used faker, since the bugfoo.com email is Blocked.
> Forefront fixed

- gpt4free/forefront/__init__.py
Fix for forefront service. Fixed "Failed to create account!" error.
> forefront fix

- gpt4free/you/__init__.py
- requirements.txt
1. added retry for you in case it didn't get the response
> added retry for you

- README.md
- gui/README.md
Adds notes about the streamlit app and the tracking it does.  It may be possible to disable if we wanted to provide that guidance.
> README.md disclaimers analytic data

- README.md
update readme to ask the user to install ffmpeg and set proxy if needed.
> feat: update readme to install ffmpeg and set proxy

- gpt4free/usesless/README.md
- gpt4free/usesless/__init__.py
- gpt4free/usesless/account_creation.py
Add token generation, may fix #582 and #579 (?)
> Usesless: add token generation

- gpt4free/usesless/__init__.py
```
message_id = mail_client.message_list()[0]["id"]  # <--- Error raised here
IndexError: list index out of range
```
```
...
while True:
time.sleep(5)
messages = mail_client.message_list()
if not messages or len(messages) == 0:
continue
...
```
```
...
while True:
time.sleep(5)
messages = mail_client.message_list()
if not messages or len(messages) == 0:
continue
message_id = messages[0]["id"]  # <--- Error was here
message = mail_client.message(message_id)
verification_url = re.findall(
r"http:\/\/ai\.usesless\.com\/api\/cms\/auth\/email-confirmation\?confirmation=\w.+\w\w",
message["text"],
)[0]
if verification_url:
break
...
```
**_No need to test the snippet. Code was tested just by running and it prevents IndexError. However, the confirmation message is not being received on …
> Fixed error in gpt4free/usesless/__init__.py [IndexError: list index out of range]

- gpt4free/hpgptai/__init__.py
RestNonce automatically changes every day and requires requesting the webpage to obtain the restNonce value
> Automatically obtain restNonce

- gpt4free/usesless/README.md
- gpt4free/usesless/__init__.py
- gpt4free/usesless/account.json
- gpt4free/usesless/test.py
- gpt4free/usesless/utils/__init__.py
- **Refactored account and mail creation**
- **Changed temporary mail service (it works without external packages)**
**_Now `usesless` fully operates._**
`Hope I could help y'all!`
> Fixed entire usesless (huge update)

- gpt4free/aicolors/__init__.py
`from typings import AiColorsResponse`
`from .typings import AiColorsResponse`
`Now, it perfectly works!`
> Update __init__.py (refactored import)

- Dockerfile
- requirements.txt
These changes will help us maintain a more secure and reliable Docker environment.
> Update Dockerfile and requirements.txt to improve security and reduce vulnerabilities

- gpt4free/gptworldAi/__init__.py
Parameter addition uuid
```python
data = json.dumps({
"messages": messages,
"frequency_penalty": 0,
"max_tokens": 4000,
"model": "gpt-3.5-turbo",
"presence_penalty": 0,
"temperature": 1,
"top_p": 1,
"stream": True,
"uuid": str(uuid.uuid4())
})
```
> Parameter addition uuid

- gpt4free/quora/api.py
This was due to a change with Poe. They changed the availableBots key to viewerBotList in the viewer data.
> Fix: Exception in thread & KeyError: 'displayName'

- gpt4free/usesless/__init__.py
> Fix for issue #660

- g4f/Provider/Providers/Lockchat.py
Recently, I changed to new domain and this provider worked.
> Fix: change subDomain of LockChat

- README.md
- g4f/Provider/Providers/AItianhu.py
- g4f/Provider/Providers/Acytoo.py
- g4f/Provider/Providers/DFEHub.py
- g4f/Provider/Providers/EasyChat.py
- g4f/Provider/__init__.py
1. AItianhu
2. EasyChat
3. Acytoo
4. DFEHub
> added some more providers

- g4f/Provider/Providers/H2o.py
Fix empty H2o output
Issue 735
https://github.com/xtekky/gpt4free/issues/735
> Fix empty H2o output

- testing/wewordle/README.md
- testing/wewordle/Wewordle.py
- testing/wewordle/testing.py
https://github.com/xtekky/gpt4free/issues/40#issuecomment-1629152431
Initially I wanted to try the API from https://chat-gpt.com/chat but i dont know how to bypass daily limit, so i tried to take a look at their android app and i got the API and was able to bypass the limit by randomizing the User and App id
api host both web and android is [wewordle ](https://wewordle.org) so i give provider name Wewordle
> add wewordle (reverse from android app)

- .vscode/settings.json
- testing/binghuan/BingHuan.py
- testing/binghuan/README.md
- testing/binghuan/helpers/binghuan.py
- testing/binghuan/testing.py
https://github.com/xtekky/gpt4free/issues/40#issuecomment-1630946450
flow chat process is realy like real Bing (create conversation,listern to websocket and more)
so i just use code Bing Provider from https://gitler.moe/g4f/gpt4free/ version and replace API endpoint and some `conversationstyles` and work fine
but bing dont realy support multi/continues conversation (using prompt template from original Provider : https://github.com/xtekky/gpt4free/blob/e594500c4e7a8443e9b3f4af755c72f42dae83f0/g4f/Provider/Providers/Bing.py#L322)
also i have problem with emoji encoding idk how to fix that, for now response from helper will encoding with utf-8 if got UnicodeEncodeError
> BingHuan (Bing China)

- testing/aiservice/AiService.py
- testing/aiservice/README.md
- testing/aiservice/testing.py
https://github.com/xtekky/gpt4free/issues/40#issuecomment-1629152431
probably gpt-3.5
> add AiService

- requirements.txt
> [-] Update requirements.txt

- g4f/Provider/Providers/DfeHub.py
DfeHub is rate-limiting now, so I have added a temporary workaround that waits for the cooldown period before sending more requests
> Update Provider.DfeHub to consider rate-limit

- .gitignore
- requirements.txt
> Fix the import errors

- g4f/Provider/Providers/AItianhu.py
- g4f/Provider/Providers/Ails.py
- g4f/Provider/Providers/ChatgptLogin.py
- g4f/Provider/Providers/DfeHub.py
- g4f/Provider/Providers/EasyChat.py
- g4f/Provider/Providers/Lockchat.py
I noticed that some of the functions took a "temperature" parameter but didn't use the specified parameter
And some providers allowed using a "temperature" parameter, but that value couldn't be specified through kwargs
So I decided to fix that. 
And also some that allowed top_p, presence_penalty, frequency_penalty.
> Use temperature parameter passed to function 

- .vscode/settings.json
- README.md
- g4f/__init__.py
- g4f/models.py
@xtekky 
It is an anti-pattern to have a large number of classes with the same attributes. Therefore, I have refactored the code to have only one Model class and made all other classes instances of that class.
I have made these modifications while ensuring compatibility with the existing implementation as much as possible.
> refactor models file

- README.md
- g4f/Provider/Providers/opchatgpts.py
- g4f/Provider/__init__.py
I've written the required code to make a new addition to the `providers` list; [opchatgpts](https://opchatgpts.net). I was unable to find a configuration of yield that didn't produce an error but other providers just used return so I believe I'm fine. Please recommend any changes I should make in order to improve my code.
> Add opchatgpts.net support

- g4f/Provider/Providers/Raycast.py
- g4f/Provider/__init__.py
Need Bearer for authorization.
> Add Raycast Provider

- README.md
I was getting a typo error with the latest version. It turns out that the provider starts with capital P.
> Provider starts with uppercase | change provider to Provider

- g4f/Provider/EasyChat.py
fix forbidden error
```bash
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://chat4.fastgpt.me/api/openai/v1/chat/completions
```
add one server `https://gxos1h1ddt.fastgpt.me`
update response check (status, length, etc) and exception
> update header & response easychat

- g4f/Provider/Theb.py
now to access https://beta.theb.ai we need login
we need bearer token and org_id for auth parameter
```python
response = g4f.ChatCompletion.create(
model="gpt-3.5-turbo",
provider=g4f.Provider.Theb,
messages=[{"role": "user", "content": "hello"}],
auth={
"bearer_token":"eyJhb....long_token",
"org_id":"....some_uuid_code"
},
)
```
to get bearer token and ord_id go to  https://beta.theb.ai, after login/register open dev tool and open network tab, try send one chat/message to ai
> fix theb but need auth

- g4f/Provider/EasyChat.py
based problem in https://github.com/xtekky/gpt4free/pull/827#issuecomment-1690770477
> fix easychat stream : remove whitspace from data: and raise exception

- README.md
I've created a project that uses `gpt4free` for **auto translation** task.
This action will automatically update and push README.md for different language. For example:
1. push `README.zh-TW.md` (zh-tw version)
2. use `gpt4free` to translate
3. generate the `README.md` (en version)
4. auto commit and push translating version.
The [link](https://github.com/Lin-jun-xiang/action-translate-readme) has been added.
> Add related project

- README.md
- g4f/Provider/AItianhu.py
- g4f/Provider/Acytoo.py
- g4f/Provider/AiService.py
- g4f/Provider/DfeHub.py
- g4f/Provider/FastGpt.py
- g4f/Provider/H2o.py
- g4f/Provider/V50.py
- g4f/Provider/Wewordle.py
- g4f/Provider/You.py
- testing/test_providers.py
- tool/readme_table.py
Improve tool/readme_table.py: added live check
Improve testing/test_providers.py: Added colors
Fix You Provider
Disable V50 Provider
Update provider urls in table
> Improve providers

- g4f/Provider/AItianhu.py
- g4f/Provider/AiService.py
- g4f/Provider/Aichat.py
- g4f/Provider/Bing.py
- g4f/Provider/ChatgptAi.py
- g4f/Provider/Theb.py
- g4f/Provider/V50.py
* Accelerate string concatenation.
* A better approach is to use the `.join()` method of strings instead of `+=`, which reduces string concatenation operations and improves performance.
* Additionally, using formatted strings (`f-strings`) makes the code cleaner and more readable.
* [PEP8: Programming Recommendations](https://peps.python.org/pep-0008/#programming-recommendations)
```python
import time
from functools import wraps
def timeit(func):
@wraps(func)
def wrapper(*arg, **kwarg):
time_start = time.time()
value = func(*arg, **kwarg)
time_end = time.time()
time_spend = time_end - time_start
print(f"[{func.__name__}] function cost time: {time_spend}")
return value
return wrapper
@timeit
def before(messages):
chat = ''
for message in messages:
chat += '%s: %s\n' % (message['role'], …
```
> Following PEP8, use `.join()` to process `messages`

- g4f/typing.py
- requirements.txt
The solution about #886 
Reference: https://github.com/python/typeshed/issues/3500
> Fix: `TypedDict` from `typing` error #886

- README.md
* According to related issues, the Python version requirement should be specified as 3.10 in `README.md`.
* Close #723
* #720 
* #871 
* #823
> Documentation: specify Python version 3.10 requirement in `README.md` (#723)

- g4f/models.py
added model config : gpt-3.5-turbo-0613
> added model config : gpt-3.5-turbo-0613

- g4f/Provider/Aivvm.py
- g4f/__init__.py
- g4f/models.py
and TypeError: issubclass() arg 1 must be a class
> Fix: Aivvm: KeyError: ''

- g4f/Provider/Liaobots.py
- g4f/Provider/Myshell.py
- g4f/Provider/OpenAssistant.py
- g4f/Provider/OpenaiChat.py
- g4f/Provider/__init__.py
- g4f/models.py
> Add Myshell Provider

- g4f/Provider/Aibn.py
- g4f/Provider/ChatgptDuo.py
- g4f/Provider/PerplexityAi.py
- g4f/Provider/Vercel.py
- g4f/Provider/__init__.py
- g4f/Provider/base_provider.py
- g4f/Provider/helper.py
- g4f/__init__.py
- g4f/models.py
- g4f/requests.py
Add support for "nest_asyncio",
Reuse event_loops with event_loop_policy
Support for  "create_async" with synchron provider
> Add ChatgptDuo and Aibn Provider

- g4f/Provider/Aivvm.py
- g4f/models.py
- testing/test_chat_completion.py
Edit: this fixes https://github.com/xtekky/gpt4free/issues/951
> Fix Aivvm and add new models in models.py

- g4f/Provider/AItianhu.py
- g4f/Provider/AItianhuSpace.py
- g4f/Provider/Aibn.py
- g4f/Provider/Aivvm.py
- g4f/Provider/ChatForAi.py
- g4f/Provider/ChatgptDuo.py
- g4f/Provider/FreeGpt.py
- g4f/Provider/HuggingChat.py
- g4f/Provider/PerplexityAi.py
- g4f/Provider/Wewordle.py
- g4f/Provider/Ylokh.py
- g4f/Provider/__init__.py
- g4f/Provider/helper.py
- g4f/models.py
- g4f/requests.py
- testing/test_async.py
- testing/test_providers.py
Impersonate Aivvm Provider
Add ChatForAi and FreeGpt Provider
Improve StreamRequest Class
> Update HuggingChat to new api

- g4f/Provider/Bing.py
- g4f/Provider/OpenaiChat.py
- g4f/Provider/helper.py
Add retry create conversation
Removed get_cookies fallback
Add creative tone parameter
> Bing Updates:

- README.md
- g4f/Provider/Cromicle.py
- g4f/models.py
added cromicle.top, gpt 3.5 provider with stream and no auth
> Add new Provider

- README.md
kinda summarizing #40 and #802 + adding proxy services that provide "free GPT-4" as well, albeit at their own terms
would probably be a cool addition to have people both a provider list, free apis list (for those that don't want to 'selfhost'), and this, for those that can self host, and simply take the amazing work of @hlohaus & @xtekky for their own use lol
> add free ai apis & potential providers list 

- g4f/Provider/AiAsk.py
- g4f/Provider/ChatgptX.py
> Fix: TypeError: 'type' object is not subscriptable

- g4f/models.py
imort AItianhu and AItianhuSpace in models.py needed line 65
> fix import in models

- g4f/gui/server/backend.py
> fix typo in backend.py

- README.md
Although the steps are given to activate the Python virtual environment, it is necessary to add an official link for that as the official documentation will provide one-to-one steps, complete with detailed explanations and best practices to ensure a seamless virtual environment setup.
> added venv documentation link

- README.md
Updated the LICENSE section in the README file to enhance the presentation. Added a GNU GPL logo, license badge and added cleaner format text table, including a hyperlink to the LICENSE file.
> chore: update LICENSE section in README

- g4f/api/run.py
- g4f/cli.py
> fix bug - Cannot assign requested address

- g4f/Provider/Bing.py
- requirements.txt
Here it is, a much-needed update to this service which offers numerous functionalities that the old code was unable to deliver to us.
As you may know, ChatGPT Plus subscribers now have the opportunity to request image analysis directly from GPT within the chat bar. Bing has also integrated this feature into its chatbot. With this new code, you can now provide an image using a data URI, with all the following supported extensions: jpg, jpeg, png, and gif!
**What is a data URI and how can I provide an image to Bing?**
Just to clarify, a data URI is a method for encoding data directly into a URI (Uniform Resource Identifier). It is typically used for embedding small data objects like images, text, or other resources within web pages or documents. Data URIs are widely used in web …
> Major Update for Bing - Supports latest bundle version and image analysis

- g4f/Provider/Bing.py
I used this repository (https://github.com/waylaidwanderer/node-chatgpt-api/) as a reference to fix all the bugs related to Bing "personality." I included all the required fields in the allowedMessageTypes and optionsSets (as well as sliceIds) to allow it to respond to any requests it actually supports.
Will also finish the code to fully implement the image generation functionality.
> Bugfix Bing.py - Resolved Issues with system prompt, Bing personalities and enabled all supported user requests

- README.md
Numbering Starting with 0 ,1 ,2 ,3 
i changed to 1 ,2 ,3 4.....
> fix: bullet point numbering mistakes resolved

- README.md
- Notes are now highlighted
- README kinda looks good now
> README.md: enhancement

- README.md
Checking token provider name and g4f available path.
> docs(README): current available link Provider path

- README.md
Please review my contribution  @xtekky
> Improved Readability and Grammar

- g4f/Provider/ChatBase.py
The text of error responses is dynamically created by LLM. Need determine by keywords for more precise identification.
> Extract keywords from incorrect responses

- LEGAL_NOTICE.md
> LEGAL_NOTICE.md

- g4f/gui/client/html/index.html
- g4f/gui/server/backend.py
- requirements.txt
change to the model that received from user interactive from the web interface model selection.
> Update backend.py, index.html, requirements.txt

- README.md
Added "Back to Top" button in the Readme.md file.
**Description**
As the readme.md is very huge and log this button will help the users to scroll to top in just one click .
> Add "Back to Top" in Readme.md

- README.md
Yqcloud is marked as inactive, but it works for me (also works from cloud hosting)
> Mark Yqcloud as active

- g4f/Provider/Bing.py
Removed unnecessary "await" statements that could potentially lead to errors
> Fix Bing.py

- g4f/Provider/needs_auth/OpenaiChat.py
> Fix NotImplementedError on WIn

- g4f/__init__.py
- g4f/api/__init__.py
- g4f/api/run.py
- g4f/cli.py
- requirements.txt
- setup.py
- Made the API ``__init__`` module use FastAPI.
- Made the CLI mode compatible with the new API code.
- Made the ``run`` module compatible with the new API code.
> Make the API use FastAPI instead of Flask

- README.md
- etc/testing/_providers.py
- etc/tool/readme_table.py
- g4f/Provider/MyShell.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/models.py
- requirements.txt
> Add auto_continue to OpenaiChat

- g4f/api/__init__.py
> Refactor item_data update to handle byte keys and convert messages to dict

- g4f/api/__init__.py
Added back list_ignored_providers parameter to ChatCompletion.create method in api.
Fixes bug from #1213
> Fix ignored providers in api

- g4f/Provider/GPTalk.py
The GPTalk have **5 times limit**. (#1255 )
Therefore, we should **re-generate `token` for `_auth` if over 5 times.**
```python
import g4f
g4f.debug.logging = True
def test():
print(
g4f.ChatCompletion.create(
model='gpt-3.5-turbo',
messages=[{"role": "user", "content": "hello"}],
provider=g4f.Provider.GPTalk
)
)
[test() for _ in range(10)]
```
```python
Using GPTalk provider
Hello! How can I assist you today?
Using GPTalk provider
Hello! How can I assist you today?
Using GPTalk provider
Hello! How can I assist you today?
Using GPTalk provider
Hello! How can I assist you today?
Using GPTalk provider
Hello! How can I assist you today?
Using GPTalk provider
Traceback (most recent call last):
File "test.py", line 25, in <module>
[test() for _ in range(10)]
File "test.py", line 25, in …
```
> Fix: GPTalk can only use 5 times

- g4f/api/__init__.py
The parameter name must be "ignored", not "list_ignored_providers"
> Fixed tupo in list_ignored_providers parameter.

- g4f/Provider/AItianhuSpace.py
- g4f/Provider/MyShell.py
- g4f/Provider/PerplexityAi.py
- g4f/Provider/Phind.py
- g4f/Provider/TalkAi.py
- g4f/Provider/helper.py
- g4f/Provider/needs_auth/Bard.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/Poe.py
- g4f/Provider/needs_auth/Theb.py
- g4f/requests.py
- requirements.txt
Update Providers with WebDriver
Add WebDriverSession helper
Use native streaming in curl_cffi
> Add Response Handler to OpenaiChat

- g4f/Provider/GptGo.py
> Fix tupo in GptGo

- g4f/Provider/deprecated/VoiGpt.py
VoiGpt is no longer working, at least for me. It just hangs for a long time and then says "Gateway timeout":
> VoiGpt stopped working -> changed the working flag to False and moved it to deprecated providers.

- g4f/models.py
Add Mistral models from HuggingChat
> Add Mistral models

- g4f/api/__init__.py
I add a option to api so it can recieve providers via http request
based on https://github.com/xtekky/gpt4free/issues/1338
> Recieve providers in api

- g4f/Provider/Bing.py
- g4f/models.py
Adds support for new model in Bing Chat. Disabled by default.
> Bing: Add support for GPT-4 Turbo model

- g4f/Provider/Aura.py
- g4f/Provider/__init__.py
Created a new Provider for Aura by Openchat which provides a free GPT 3.5 based model.
Closes #1369
> Added OpenChat's Aura Model as a new Provider

- g4f/Provider/Phind.py
- Adds challenge parameter in request body to match requests made on the Phind web app
- Prevents new <PHIND_INDICATOR> tag from being added to response body
Not really sure what the challenge parameter does but the value I added is roughly what they use for all the requests on phind web ui
> Fix Phind provider

- g4f/Provider/Chatxyz.py
- g4f/Provider/__init__.py
Added a new Provider based on GPT 3.5 turbo model. 
#1375
> Added new Provider Chatxyz

- g4f/Provider/Bestim.py
- g4f/Provider/__init__.py
New BaseProvider 'Bestim' from [this comment](https://github.com/xtekky/gpt4free/issues/802#issuecomment-1873032520)
> New Provider 'Bestim'

- g4f/Provider/bing/__init__.py
The folder bing was not getting recognised as a module since it's missing init file. Added that.
Fixes #1446
> Fixed Error "No module named g4f.Provider.bing"

- g4f/Provider/FreeChatgpt.py
- g4f/models.py
Merged changes from NextChat to FreeChatgpt.
Added more models and optimised request body and headers.
Fixes #1424
> Added support for more models: FreeChatgpt

- g4f/Provider/Bing.py
- g4f/Provider/bing/upload_image.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/gui/client/css/style.css
- g4f/gui/client/js/chat.v1.js
- g4f/image.py
Add ImageResponse to Bing
Fix cursor styling in gui
> Fix process_image in Bing

- .github/workflows/unittest.yml
- etc/unittest/main.py
- g4f/Provider/Bing.py
- g4f/Provider/FreeChatgpt.py
- g4f/Provider/Phind.py
- g4f/Provider/base_provider.py
- g4f/Provider/bing/conversation.py
- g4f/Provider/bing/create_images.py
- g4f/Provider/bing/upload_image.py
- g4f/Provider/create_images.py
- g4f/Provider/helper.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/retry_provider.py
- g4f/__init__.py
- g4f/base_provider.py
- g4f/gui/client/css/style.css
- g4f/gui/client/html/index.html
- g4f/gui/client/js/chat.v1.js
- g4f/gui/server/backend.py
- g4f/image.py
- g4f/models.py
- g4f/requests.py
- g4f/version.py
- g4f/webdriver.py
Add doctypes to many functions
Add file upload for text files
Add alternative url to FreeChatgpt
Add webp to allowed image types
> Refactor code with AI

- g4f/Provider/Llama2.py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 6
> Llama2.py result decode error：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 6

- README.md
> Web UI Instructions, Update README.md

- etc/tool/copilot.py
- g4f/Provider/PerplexityLabs.py
- g4f/Provider/__init__.py
- g4f/Provider/bing/upload_image.py
- g4f/gui/client/html/index.html
- g4f/gui/client/js/chat.v1.js
- g4f/gui/server/backend.py
- g4f/image.py
- g4f/models.py
Fix upload image in Bing Provider
> Add upload svg image support

- README.md
Added example POST request to docs. Looks like this:
> Update README.md with POST example

- etc/unittest/backend.py
- g4f/Provider/Aura.py
- g4f/Provider/Bestim.py
- g4f/Provider/Chatgpt4Online.py
- g4f/Provider/PerplexityLabs.py
- g4f/Provider/base_provider.py
- g4f/Provider/bing/create_images.py
- g4f/Provider/helper.py
- g4f/Provider/needs_auth/Bard.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/Poe.py
- g4f/Provider/needs_auth/Theb.py
- g4f/Provider/selenium/AItianhuSpace.py
- g4f/Provider/selenium/PerplexityAi.py
- g4f/Provider/selenium/TalkAi.py
- g4f/__init__.py
- g4f/debug.py
- g4f/errors.py
- g4f/gui/__init__.py
- g4f/gui/client/js/chat.v1.js
- g4f/gui/server/backend.py
- g4f/requests.py
- g4f/requests_aiohttp.py
- g4f/requests_curl_cffi.py
- g4f/webdriver.py
Add set_cookies helper, Show last used model
> Fix: ChromeDriver only supports characters in the BMP

- README.md
- docker/Dockerfile
- etc/unittest/asyncio.py
- etc/unittest/main.py
- g4f/Provider/Bing.py
- g4f/Provider/bing/create_images.py
- g4f/Provider/bing/upload_image.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/defaults.py
- g4f/gui/client/js/chat.v1.js
- g4f/image.py
- g4f/requests.py
- g4f/requests_aiohttp.py
- g4f/typing.py
- g4f/webdriver.py
- requirements.txt
Fix preview for uploaded and generated images in gui
Improve typing, readme
> Add aiohttp_socks to requirements

- g4f/Provider/DeepInfra.py
> Fix DeepInfra: Model is not supported

- README-DE.md
- README.md
- g4f/Provider/FakeGpt.py
- g4f/Provider/GeekGpt.py
> Change GeekGPT and FakeGPT status to inactive as owner statement

- g4f/Provider/CreateImagesBing.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/cookies.py
- g4f/webdriver.py
> Read cookies from config in Gemini

- README.md
Addresses the concern discussed #1553
> Add python-tgpt to related projects

- g4f/Provider/create_images.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/image.py
Fix issue in Bing Image Decorator
> Improve preview in image generation of Gemini

- g4f/Provider/Bing.py
Needs to be tested, if this addition is not made, bing will not work well enough
> Update Bing Sets

- g4f/__init__.py
- g4f/api/__init__.py
> Set default values for generation config

- g4f/gui/client/css/style.css
- g4f/gui/client/js/chat.v1.js
Improve hidding regenerated messages
> Add remove messages from history

- g4f/Provider/AiChatOnline.py
- g4f/Provider/Aura.py
- g4f/Provider/ChatgptAi.py
- g4f/Provider/ChatgptDemo.py
- g4f/Provider/ChatgptNext.py
- g4f/Provider/Chatxyz.py
- g4f/Provider/FlowGpt.py
- g4f/Provider/GeminiPro.py
- g4f/Provider/You.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/__init__.py
- g4f/client.py
- g4f/providers/base_provider.py
- g4f/providers/retry_provider.py
- g4f/providers/types.py
- g4f/typing.py
Add fetch access_token and fix cookie usage in OpenaiChat
Fix save created access_token in cookies in OpenaiChat
Add use_auth_header config in GeminiPro
> Add support for message history and system message in OpenaiChat

- README.md
- g4f/Provider/Liaobots.py
Their website is showing a 404 page
See yourself: https://liaobots.work
> Mark Liaobots Provider as inactive

- g4f/Provider/GeminiPro.py
- g4f/Provider/bing/conversation.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/gui/client/css/style.css
- g4f/gui/client/html/index.html
- g4f/gui/client/js/chat.v1.js
Map system messages to user messages in GeminiPro
> Expire cache, Fix multiple websocket conversations in OpenaiChat

- g4f/Provider/BingCreateImages.py
- g4f/Provider/HuggingChat.py
- g4f/Provider/HuggingFace.py
- g4f/Provider/Llama2.py
- g4f/Provider/PerplexityLabs.py
- g4f/Provider/You.py
- g4f/Provider/__init__.py
- g4f/Provider/bing/create_images.py
- g4f/client.py
- g4f/image.py
- g4f/models.py
- g4f/providers/base_provider.py
Add more models and image generation in You provider Use You as second default image provider
> Fix HuggingChat and PerplexityLabs and add HuggingFace provider

- g4f/Provider/Vercel.py
Sorry I submitted three times (because I tried to submit directly through the file, but it seemed to fail), this PR fixes Vercel's UnicodeDecodeError error so that the answer no longer interrupts
> Error checking for Vercel

- README.md
- g4f/Provider/HuggingChat.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/openai/crypt.py
- g4f/Provider/openai/har_file.py
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- requirements-min.txt
- requirements.txt
- setup.py
Update model list of HuggingChat
Update styles of scrollbar in gui
Fix image upload in gui
> Add .har file support for OpenaiChat

- docker/Dockerfile
1. Combined some multiple `RUN` commands to reduce Docker container layers.
2. Moved the `rm` cache cleaning command after the `apt-get` installation command for smaller layer size.
> Refactor: Optimize Dockerfile structure

- README.md
> feat: credit MetaAI

- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/you/har_file.py
- g4f/gui/client/index.html
- g4f/gui/client/static/js/chat.v1.js
Show global model list when unselect provider
> Fix issue with You.com and nodriver

- g4f/Provider/HuggingChat.py
Added `microsoft/Phi-3-mini-4k-instruct` model.
> Update models list for `HuggingChat` provider

- g4f/Provider/DeepInfra.py
- g4f/Provider/Reka.py
- g4f/Provider/Replicate.py
- g4f/Provider/You.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/PerplexityApi.py
- g4f/Provider/needs_auth/__init__.py
- g4f/Provider/you/har_file.py
- g4f/providers/retry_provider.py
> Add needs auth to provierds, Add PerplexityApi provider

- g4f/Provider/GeminiProChat.py
The url for geminiprochat has been changed so updated the Provider
repo:- https://github.com/expertbeacon/gemini-chatbot
url :- https://www.chatgemini.net/
> Update URL For GeminiProChat

- g4f/Provider/GeminiProChat.py
> #2088 issue fixed

- README.md
- g4f/Provider/Chatgpt4Online.py
- g4f/Provider/DDG.py
- g4f/Provider/FlowGpt.py
- g4f/Provider/MagickPenAsk.py
- g4f/Provider/Rocks.py
- g4f/Provider/__init__.py
fixed three providers to work in their expected fashion
> fix: 3 providers work again

- g4f/Provider/GeminiPro.py
See <https://ai.google.dev/gemini-api/docs/system-instructions?lang=rest>
> feat(GeminiPro): add support for system prompt

- g4f/api/__init__.py
https://github.com/xtekky/gpt4free/blob/main/g4f/cli.py#L40
> fix: `--ignored-providers` option not working due to variable name mismatch

- README.md
https://github.com/yjg30737/pyqt-openai
I've implemented g4f in pyqt-openai (application name is VividNode, by the way) and it works perfectly 👌
pyqt-openai is the desktop chatbot made entirely with Python.
Thanks !
> Added VividNode(pyqt-openai) to Powered by gpt4free

- g4f/cookies.py
OpenaiChat provider isn't working without this line.
> Update cookies.py to support HAR loading for OpenaiChat

- README.md
- docs/interference-api.md
1. Explain **Api server** Port binding in documentation #2320
2. Make **.har cookie** instructions clear
> Update interference api and .har cookie docs

- g4f/Provider/Mhystical.py
- g4f/Provider/__init__.py
This pull request introduces a new provider, `Mhystical`, to the `g4f` package. The changes include the implementation of the provider class and its integration into the existing provider system.
* **New provider class `Mhystical`**: Added a new provider class `Mhystical` in `g4f/Provider/Mhystical.py` with methods for model selection, asynchronous request handling, and response filtering.
* **Integration into provider system**: Included the new provider `Mhystical` in the provider initialization file `g4f/Provider/__init__.py`.
> [+] Mhystical.cc

- g4f/image.py
- g4f/providers/base_provider.py
add fix_url ( replace ' ' by '+' (to be markdown compliant))
> FIX: fix the url in the markdown output (md compliance), and the chunk/ImageResponse to str !

- .github/workflows/publish-workflow.yaml
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/openai/har_file.py
- g4f/Provider/openai/proofofwork.py
Update read har file in OpenaiChat provider
Remove webdriver in OpenaiChat provider
Add supported_encodings and supported_encodings in OpenaiChat
> Update docker tags in workfloe for slim images,

- g4f/Provider/Airforce.py
- g4f/client/__init__.py
Improve image generation in Airforce provider
> Fix provider selection in images generate

- README.md
- docs/gui.md
- etc/unittest/backend.py
- g4f/Provider/Copilot.py
- g4f/Provider/Flux.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/BingCreateImages.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/needs_auth/HuggingChat.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/MicrosoftDesigner.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/api/__init__.py
- g4f/client/__init__.py
- g4f/client/stubs.py
- g4f/cookies.py
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend.py
- g4f/image.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/providers/types.py
- g4f/requests/__init__.py
Reuse cookies and access token in Copilot
Send in the gui messages to multiple providers at once Add GUI documenation
> Use custom user data dir for each provider

- g4f/Provider/Airforce.py
- g4f/Provider/AmigoChat.py
- g4f/Provider/Copilot.py
- g4f/Provider/DDG.py
- g4f/Provider/Mhystical.py
- g4f/Provider/needs_auth/GithubCopilot.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/openai/new.py
- g4f/api/__init__.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
Ignore disabled providers in gui,
Read cookie files after upload
> Add Clarity Token to Copilot,

- g4f/Provider/Blackbox2.py
- g4f/Provider/Copilot.py
- g4f/Provider/DarkAI.py
- g4f/Provider/needs_auth/Cerebras.py
- g4f/Provider/needs_auth/Groq.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/HuggingFaceAPI.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/Provider/needs_auth/__init__.py
- g4f/Provider/needs_auth/xAI.py
- g4f/__init__.py
- g4f/api/__init__.py
- g4f/client/service.py
- g4f/cookies.py
- g4f/gui/client/index.html
- g4f/providers/retry_provider.py
Add get_models to OpenaiAPI, HuggingFace and Groq
Add xAI provider
> Improved ignored providers support,

- g4f/Provider/Airforce.py
- g4f/Provider/Copilot.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/__init__.py
- g4f/client/__init__.py
- g4f/client/helper.py
- g4f/gui/client/home.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/providers/asyncio.py
- g4f/providers/base_provider.py
- g4f/providers/retry_provider.py
- g4f/providers/types.py
- g4f/tools/run_tools.py
- g4f/tools/web_search.py
Add auth caching for OpenAI ChatGPT
Some provider improvments
> Support continue messages in Airforce

- docker/Dockerfile
- g4f/Provider/Cloudflare.py
- g4f/Provider/DDG.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/api/__init__.py
- g4f/gui/client/home.html
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/backend_api.py
- g4f/gui/webview.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/providers/response.py
- g4f/providers/retry_provider.py
- g4f/requests/__init__.py
- g4f/tools/files.py
- g4f/tools/web_search.py
- requirements.txt
- setup.py
Fix for RetryProviders doesn't retry
Add retry and continue for DuckDuckGo provider
Add cache for Cloudflare provider
Add cache for prompts on gui home
Add scroll to bottom checkbox in gui
Improve prompts on home gui
Fix response content type in api for files
> Add Edge as Browser for nodriver

- docs/requests.md
- g4f/Provider/DDG.py
- g4f/Provider/GizAI.py
- g4f/Provider/Mhystical.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/needs_auth/DeepInfra.py
- g4f/Provider/needs_auth/DeepSeek.py
- g4f/Provider/needs_auth/GlhfChat.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/__init__.py
- g4f/Provider/openai/har_file.py
- g4f/api/__init__.py
- g4f/client/__init__.py
- g4f/client/stubs.py
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/local/__init__.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/providers/response.py
- g4f/providers/retry_provider.py
- g4f/requests/__init__.py
- g4f/tools/files.py
Add none auth with OpenAI using nodriver
Fix missing 1 required positional argument: 'cls'
Update count tokens in GUI
Fix streaming example in requests guide
Remove ChatGptEs as default model
> Fix invalid escape in requests module

- docs/providers-and-models.md
> removed p1 duplicate

- g4f/Provider/Jmuz.py
- g4f/Provider/Pizzagpt.py
- g4f/Provider/needs_auth/Custom.py
- g4f/Provider/needs_auth/GeminiPro.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/api/__init__.py
- g4f/gui/client/index.html
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/models.py
Add "Custom Provider": Set  API Url in the settings
Remove Discord link from result, add them to  attr: Jmuz
Fix Bug: File content are added to the prompt
Changed response from /v1/models API
Disable Pizzagpt Provider
> Read FinishReason and Usage from Gemini API

- g4f/gui/server/api.py
- g4f/tools/run_tools.py
- requirements.txt
- setup.py
> Add missing webview requirements

- g4f/Provider/Jmuz.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/hf_space/Qwen_QVQ_72B.py
- g4f/Provider/hf_space/__init__.py
- g4f/Provider/local/Ollama.py
- g4f/Provider/needs_auth/HuggingChat.py
- g4f/Provider/needs_auth/HuggingFace.py
- g4f/Provider/needs_auth/HuggingFaceAPI.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/ThebApi.py
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/providers/base_provider.py
- g4f/providers/response.py
- g4f/requests/__init__.py
- g4f/requests/raise_for_status.py
Improve model list in HuggingSpace, PollinationsAI
Fix Image Generation in PollinationsAI
Add Image Upload in PollinationsAI
Support Usage, FinishReason,  jsonMode in PollinationsAI
Add Reasoning to Web UI
Fix using provider api_keys in Web UI
[Add RequestLogin to HuggingChat]
[Support Image Upload in HuggingChat]
> Support TitleGeneration, Reasoning in HuggingChat

- docs/async_client.md
- docs/client.md
- etc/unittest/client.py
- g4f/Provider/DDG.py
- g4f/Provider/DeepInfraChat.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/needs_auth/OpenaiAPI.py
- g4f/api/stubs.py
- g4f/client/__init__.py
- g4f/errors.py
Improve error handling in DDG
use OpenaiAPI provider in DeepInfraChat
Support api_base and response_type parameters in API
> Restore AsyncClient streaming return type

- .github/workflows/publish-workflow.yaml
- README.md
- g4f/providers/base_provider.py
Fix async_generator can't be used in 'await' expression on Windows
> Update bulding and publishing docker image for arm64

- g4f/Provider/ChatGpt.py
- g4f/Provider/Copilot.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/hf_space/Qwen_Qwen_2_5M_Demo.py
- g4f/Provider/needs_auth/CopilotAccount.py
- g4f/Provider/needs_auth/OpenaiAccount.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/needs_auth/OpenaiTemplate.py
- g4f/client/__init__.py
- g4f/client/image_models.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/image.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/providers/response.py
- g4f/providers/retry_provider.py
- g4f/requests/curl_cffi.py
- g4f/requests/raise_for_status.py
- requirements-slim.txt
- setup.py
Add model qwen-2.5-1m-demo to models.py
Add AsyncAuthedProvider in Copilot
Add orginal url to downloaded image
Support ssl argument in StreamSession
Report Provider and Errors in RetryProvider
Support ssl argument in OpenaiTemplate
Remove model duplication in OpenaiChat
Disable ChatGpt provider and remove it from models.py Update slim requirements
Support provider names as model name in Image generation
> Add model qwen-2.5-1m-demo to models.py

- g4f/gui/client/static/img/site.webmanifest
- g4f/gui/client/static/js/chat.v1.js
- g4f/tools/files.py
- g4f/tools/web_search.py
Add created buckets automatic to messages
Don't add images to scrape result without title
> Support options like max_depth in downloads.json

- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/Provider/openai/har_file.py
Use dependency injection for RequestConfig so that other can overwrite it.
> refactor: use dependency injection for RequestConfig

- g4f/Provider/DDG.py
- g4f/Provider/hf/HuggingFaceAPI.py
- g4f/Provider/hf/__init__.py
- g4f/Provider/hf/models.py
- g4f/Provider/hf_space/G4F.py
- g4f/api/__init__.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
> Fix issue with demo mode

- g4f/tools/files.py
- requirements-slim.txt
- requirements.txt
- setup.py
> Fix errors on read buckets

- g4f/Provider/needs_auth/Gemini.py
- g4f/api/__init__.py
- g4f/client/__init__.py
- g4f/gui/client/demo.html
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/backend_api.py
- g4f/gui/server/website.py
- g4f/providers/retry_provider.py
Add login button to HuggingFace demo
Custom conversation ids in chat ui
Remove rate limiter in demo mode
Improve YouTube support in Gemini
> Fix model and provider in chat completion response

- README.md
- g4f/Provider/hf/HuggingFaceInference.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/cookies.py
- g4f/gui/client/demo.html
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/models.py
- g4f/providers/asyncio.py
- g4f/providers/response.py
- g4f/tools/run_tools.py
- g4f/tools/web_search.py
Add HuggingFace provider provider
Auto refresh Google Gemini cookies
Add sources to search results
> Add new media selection in UI

- g4f/Provider/PollinationsAI.py
- g4f/providers/response.py
- Eliminate redundant Audio class implementation found in original code
- Consolidate audio response handling into single class definition
- Prevent potential conflicts from duplicated class declarations
- Add Audio class import and audio response handling in _generate_text
- Introduce separate OpenAI endpoint URL and audio model configuration
- Update model fetching to categorize audio models with available voices
- Implement voice selection for audio models using random.choice
- Modify URL routing to support both OpenAI-compatible and audio endpoints
- Add content-type detection for audio responses in text generation flow
- Remove seed parameter when using Gemini models to ensure compatibility
> Sorry for accidentally deleting your audio implementation that you added @hlohaus. Please …
>  Add Audio Generation and Response Support for AI Providers

- docs/pydantic_ai.md
- g4f/Provider/ARTA.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/client/__init__.py
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/gui/server/js_api.py
- g4f/providers/base_provider.py
- g4f/providers/tool_support.py
- g4f/tools/run_tools.py
Add ToolSupport in PollinationsAI provider
Add default value for model in chat completions
Add Streaming Support for PollinationsAI provider
> Add ARTA image provider

- g4f/Provider/ARTA.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/hf/HuggingFaceAPI.py
- g4f/__init__.py
- g4f/api/stubs.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/tools/run_tools.py
Support conversational HuggingFace providers
Fix streaming in PollinationsAI provider
> Add many parameters to API endpoints

- g4f/Provider/ARTA.py
- [fix] change model alias from "flux_black_ink" to "black_ink" in g4f/Provider/ARTA.py
- [feat] Add optional seed parameter with random generation in ARTA.
> fix: ARTA model and add optional seed parameter

- g4f/Provider/TypeGPT.py
- g4f/Provider/__init__.py
**Model support:**
- Text generation: `o3-mini, gemini-1.5-flash, deepseek-r1, gemini-pro`
> New provider added (g4f/Provider/TypeGPT.py)

- g4f/Provider/needs_auth/Reka.py
- Change old URL to new  #2806 
- Updated error messages/body content to reference cls.domain/cls.url instead of hardcoded values for better maintainability.
> Refactor Reka provider class: Update URL and url handling

- etc/examples/video.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/hf/HuggingFaceInference.py
- g4f/Provider/hf/HuggingFaceMedia.py
- g4f/Provider/needs_auth/Grok.py
- g4f/Provider/template/OpenaiTemplate.py
- g4f/api/__init__.py
- g4f/client/__init__.py
- g4f/client/image_models.py
- g4f/gui/client/background.html
- g4f/gui/client/index.html
- g4f/gui/client/qrcode.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/image/__init__.py
- g4f/image/copy_images.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/requests/raise_for_status.py
Improve handling of shared chats
Show api_key input if required
> Set default model in HuggingFaceMedia

- docs/providers-and-models.md
- g4f/Provider/Blackbox.py
- g4f/gui/client/static/css/style.css
- g4f/gui/server/backend_api.py
- g4f/models.py
- Add BlackboxAI Pro model to supported models (close #2829)
- Add model to Blackbox provider fallback models
- Fix URL redirect formatting in backend_api.py
- Update providers-and-models.md documentation
---
- Push bottom buttons to the bottom of UI
- Make chat container grow to fill space
- Ensure settings panel gets proper height
- Improve vertical spacing in the interface
> Add BlackboxAI Pro model and fix URL redirect formatting

- g4f/Provider/PollinationsAI.py
- g4f/Provider/PollinationsImage.py
- g4f/gui/client/background.html
- g4f/gui/client/index.html
- g4f/gui/client/qrcode.html
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/client/static/js/photoswipe.js
- g4f/gui/server/backend_api.py
- g4f/gui/server/website.py
- g4f/image/copy_images.py
- g4f/requests/__init__.py
Improve share js functions
Fix photoswipe in UI
Support n parameter in PollinationsAI
> Improve background page

- .github/workflows/publish-to-pypi.yml
- docs/media.md
- g4f/Provider/Cloudflare.py
- g4f/Provider/PerplexityLabs.py
- g4f/Provider/PollinationsAI.py
- g4f/Provider/TypeGPT.py
- g4f/Provider/__init__.py
- g4f/Provider/hf/HuggingFaceAPI.py
- g4f/Provider/hf/HuggingFaceMedia.py
- g4f/Provider/needs_auth/GigaChat.py
- g4f/Provider/needs_auth/OpenaiChat.py
- g4f/client/__init__.py
- g4f/debug.py
- g4f/errors.py
- g4f/gui/client/background.html
- g4f/gui/client/index.html
- g4f/gui/client/static/css/style.css
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/client/static/js/photoswipe.js
- g4f/gui/server/api.py
- g4f/gui/server/backend_api.py
- g4f/image/__init__.py
- g4f/image/copy_images.py
- g4f/models.py
- g4f/providers/base_provider.py
- g4f/providers/response.py
- g4f/requests/__init__.py
- g4f/tools/files.py
- g4f/tools/media.py
Fix lightbox for uploaded images
Fix save media content
Fix TypeGPT and Cloudflare provider
> Delete buckets with the conversation

- README.md
- docs/authentication.md
- docs/gui.md
- docs/media.md
- g4f/Provider/Cloudflare.py
- g4f/Provider/Copilot.py
- g4f/Provider/DuckDuckGo.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/CopilotAccount.py
- g4f/api/stubs.py
- g4f/gui/client/static/js/chat.v1.js
- g4f/gui/server/website.py
- g4f/image/__init__.py
- g4f/providers/response.py
- g4f/tools/web_search.py
> Support "Think Deeper" in Copilot

- g4f/Provider/PollinationsAI.py
- g4f/Provider/PollinationsImage.py
- g4f/api/__init__.py
- g4f/client/__init__.py
- g4f/client/helper.py
- g4f/requests/__init__.py
> Fix issue with new nodriver version

- docs/file.md
- g4f/Provider/ARTA.py
- g4f/Provider/AllenAI.py
- g4f/Provider/Blackbox.py
- g4f/Provider/FreeRouter.py
- g4f/Provider/__init__.py
- g4f/Provider/needs_auth/CablyAI.py
- g4f/Provider/needs_auth/Gemini.py
- g4f/Provider/needs_auth/OpenRouter.py
- g4f/Provider/needs_auth/__init__.py
- g4f/tools/files.py
- g4f/tools/run_tools.py
- g4f/typing.py
- Added file upload usage example with bucket_id in docs/file.md
- Fixed ARTA provider by refactoring error handling with a new raise_error function
- Simplified aspect_ratio handling in ARTA with proper default
- Improved AllenAI provider by cleaning up image handling logic
- Fixed Blackbox provider's media handling to properly process images
- Updated file tools to handle URL downloads correctly
- Fixed bucket_id pattern matching in ToolHandler.process_bucket_tool
- Cleaned up imports in typing.py by removing unnecessary sys import
- Fixed inconsistent function parameters in g4f/tools/files.py
- Fixed return value of upload_and_process function to return bucket_id
> feat: improve file handling and streamline provider implementations

- g4f/Provider/Cloudflare.py
**Added Models**
Added Llama-4-Scout, Deepseek-Math, Deepseek-R1-qwen-32b, falcon-7b, and qwen-2.5-coder models in Cloudflare provider.
> Added new models in Cloudflare Provider

- g4f/Provider/SearXNG.py
- g4f/tools/web_search.py
This PR extends and improves the web search system in the `gpt4free` project by introducing support for [[SearXNG](https://github.com/searxng/searxng)](https://github.com/searxng/searxng), an open-source metasearch engine. Currently, only DuckDuckGo is supported, which poses a single point of failure and has known limitations in result quantity and quality. With this PR, users can utilize either a self-hosted or a public SearXNG instance to gain more reliable and customizable search results.
- New provider `SearXNG` implemented in `g4f/Provider/SearXNG.py`
- Extension of `web_search.py` to include:
- Optional `provider` key in `tool_calls` arguments
- DuckDuckGo remains the default if `provider` is not specified
- If `"provider": "SearXNG"` is specified, the custom provider is used
- Code …
> Add Support for Web Search via SearXNG

- README.md
- g4f/Provider/Cloudflare.py
- g4f/Provider/audio/MarkItDown.py
- g4f/Provider/needs_auth/Grok.py
- g4f/api/__init__.py
- Added validation for `media` parameter in `MarkItDown` class to raise `ValueError` if `media` is not provided.
- Included a check for `has_markitdown` in `MarkItDown` class to raise `ImportError` if `markitdown` is not installed.
- Refactored API response structure by defining `responses` as a reusable dictionary in `g4f/api/__init__.py`.
- Updated `/v1/chat/completions` endpoint to include a new parameter `conversation_id` in the `chat_completions` function.
- Enhanced logic in `chat_completions` to set `conversation_id` from configuration or function input.
- Added a new endpoint `/api/{provider}/{conversation_id}/chat/completions` in `g4f/api/__init__.py` to handle chat completions with `conversation_id`.
- Replaced duplicate response dictionary definitions with the reusable …
> feat: Improve handling of media and API response structures

- g4f/Provider/needs_auth/DeepSeekAPI.py
- g4f/Provider/needs_auth/Grok.py
- g4f/gui/server/backend_api.py
- g4f/gui/server/website.py
- g4f/image/__init__.py
- g4f/integration/markitdown/__init__.py
- g4f/integration/markitdown/_transcribe_audio.py
- g4f/providers/helper.py
- g4f/tools/files.py
- g4f/tools/media.py
- Added UUID-based "x-xai-request-id" header and 403 error handling in Grok.py
- Updated backend_api.py to handle empty media results and unsupported file types with error raising and file cleanup
- Simplified render logic in website.py by removing is_live flag and related code
- Changed "audio/wav" MIME type to "audio/x-wav" in image/__init__.py
- Added is_valid_media and is_valid_audio functions to image/__init__.py for stricter media validation
- Enhanced MarkItDown integration in markitdown/__init__.py with convert_stream method supporting non-seekable streams
- Modified _transcribe_audio.py to use recognize_faster_whisper if available, fallback to recognize_google
- Updated providers/helper.py to prioritize "text" key in to_string function
- Improved stream_read_files in files.py to …
> feat: improve media handling, file conversion, and error management
